/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.InstructorFrames.InstructorGenFrames;




import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

import java.text.SimpleDateFormat;

import java.util.*;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

import main.util.API_Actions.ListarUsuarios;
import main.util.InstructorMethods.InstructorAsisDocs.UploadFileAPI;
import main.util.models.CustomCellRenderer;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import main.InstructorFrames.InstructorHomeScreen;
import main.util.API_Actions.ConvertirDatos;
import main.util.API_AdminActions.API_Admin_BuscarUsuario;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.json.JSONObject;

import main.util.models.ComboBoxModels;
import main.util.models.UserSession;
import org.apache.poi.ss.usermodel.ComparisonOperator;
import org.apache.poi.ss.usermodel.ConditionalFormattingRule;
import org.apache.poi.ss.usermodel.PatternFormatting;
import org.apache.poi.ss.usermodel.SheetConditionalFormatting;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFColor;
import org.apache.poi.xssf.usermodel.XSSFPatternFormatting;


/**
 *
 * @author Propietario
 */
public class ExcelGenFrame extends javax.swing.JFrame {

    /**
     * Creates new form ExcelGenFrame
     */
    public DefaultTableModel modeloTabla;
    public DefaultTableModel ListarAprendicesModel;
    public Workbook workbook;
    public Sheet sheet;
    public int rowNum;
    private CustomCellRenderer cellRenderer = new CustomCellRenderer();
    
    public ExcelGenFrame() {
        initComponents();
        modif();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InstructorNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        HoraFin = new javax.swing.JLabel();
        HoraInicio = new javax.swing.JLabel();
        IngresoCodAprendiz = new javax.swing.JTextField();
        RegistrarAsistencia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAsis = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        FinalizarAsis = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Competencia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ProgramaFormacionCB = new javax.swing.JComboBox<>();
        FichaCB = new javax.swing.JComboBox<>();
        AmbienteCB = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListarAprendices = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Instructor:");

        InstructorNombre.setText("XXXXXXXXXXXXXXXXXX");

        jLabel3.setText("Fecha Fin:");

        jLabel4.setText("Fecha Inicio:");

        HoraFin.setText("XX:XX");

        HoraInicio.setText("XX:XX");

        IngresoCodAprendiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoCodAprendizActionPerformed(evt);
            }
        });

        RegistrarAsistencia.setText("Registrar Asistencia");
        RegistrarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarAsistenciaActionPerformed(evt);
            }
        });

        tablaAsis.setBackground(new java.awt.Color(255, 255, 255));
        tablaAsis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Tipo de Documento", "Documento", "Programa formacion", "Nivel formacion", "Competencia", "Hora de Ingreso", "Estado de asistencia"
            }
        ));
        tablaAsis.setFocusable(false);
        tablaAsis.setName(""); // NOI18N
        tablaAsis.setRowHeight(44);
        tablaAsis.setRowSelectionAllowed(false);
        tablaAsis.setSelectionBackground(new java.awt.Color(215, 213, 177));
        jScrollPane1.setViewportView(tablaAsis);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        FinalizarAsis.setText("Finalizar asistencia");
        FinalizarAsis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarAsisActionPerformed(evt);
            }
        });

        jLabel5.setText("Competencia");

        jLabel6.setText("Ambiente");

        jLabel7.setText("Ficha");

        jLabel8.setText("Programa de Formacion");

        ProgramaFormacionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ProgramaFormacionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgramaFormacionCBActionPerformed(evt);
            }
        });

        FichaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        FichaCB.setEnabled(false);
        FichaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FichaCBActionPerformed(evt);
            }
        });

        AmbienteCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ListarAprendices.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ListarAprendices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Documento", "Aprendiz"
            }
        ));
        ListarAprendices.setFocusable(false);
        ListarAprendices.setRequestFocusEnabled(false);
        ListarAprendices.setRowHeight(40);
        ListarAprendices.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(ListarAprendices);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AmbienteCB, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Competencia, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(InstructorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(HoraFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ProgramaFormacionCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FichaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(355, 355, 355)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FinalizarAsis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IngresoCodAprendiz)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1286, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .addComponent(RegistrarAsistencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(InstructorNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(Competencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ProgramaFormacionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(HoraInicio)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(HoraFin)
                                    .addComponent(jLabel7)
                                    .addComponent(FichaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(AmbienteCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FinalizarAsis, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngresoCodAprendiz)
                    .addComponent(RegistrarAsistencia, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void modif(){
        InstructorNombre.setText(UserSession.getInstance().getNombres());

        workbook = new XSSFWorkbook(); // O cualquier otra inicialización necesaria
        sheet = workbook.createSheet("Asistencia");
        modeloTabla = new DefaultTableModel(
            new Object[][] {},
            new String[] {
                "Nombres", "Apellidos", "Tipo Documento", "Documento", "Programa Formación", "Nivel Formación", "Curso", "Fecha", "Estado"
            }
        );
        tablaAsis.setModel(modeloTabla);
        ComboBoxModels ComboBoxModels = new ComboBoxModels();
        
        try {
            List<String> tiposProgramaFormacion = ComboBoxModels.BoxProgramaFormacionModel();
            if (tiposProgramaFormacion == null) {
                JOptionPane.showMessageDialog(null, "Hubo un error cargando los programas de formacion de la API");
            } else {
                tiposProgramaFormacion.add(0, "Seleccionar...");
                DefaultComboBoxModel<String> ProgramaFormacionBoxModel = new DefaultComboBoxModel<>(ComboBoxModels.toArray(tiposProgramaFormacion));
                ProgramaFormacionCB.setModel(ProgramaFormacionBoxModel);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        try {
            List<String> tiposAmbientes = ComboBoxModels.BoxAmbientesModel();
            if (tiposAmbientes == null) {
                JOptionPane.showMessageDialog(null, "Hubo un error cargando los Ambientes de la API");
            } else {
                tiposAmbientes.add(0, "Seleccionar...");
                DefaultComboBoxModel<String> AmbientesBoxModel = new DefaultComboBoxModel<>(ComboBoxModels.toArray(tiposAmbientes));
                AmbienteCB.setModel(AmbientesBoxModel);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        

        
        this.setLocationRelativeTo(null);
        IngresoCodAprendiz.requestFocusInWindow();
        HoraInicio.setText(String.valueOf(HoraActual()));
        HoraFin.setText(String.valueOf(HoraInasistencia()));
    }

    private void initializeTable() {
        ListarAprendices.setDefaultRenderer(Object.class, new CustomCellRenderer());
    }
    
    
    public String HoraActual(){
        Calendar calendar = Calendar.getInstance();
        Date fechaActual = new Date();

        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm a");
        // Obtener la hora actual formateada en XX:XX AM/PM
        String horaFormateada = sdf.format(fechaActual);
        return horaFormateada;
    }
    
    public String HoraTardia(){
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.HOUR_OF_DAY, 1);
        Date fechaEn5Horas = calendar.getTime();
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm a");
        String horaFin = sdf.format(fechaEn5Horas);
        return horaFin;
    }
    
    
    public String HoraInasistencia(){
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.HOUR_OF_DAY, 5);
        Date fechaEn5Horas = calendar.getTime();
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm a");
        String horaFin = sdf.format(fechaEn5Horas);
        return horaFin;
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        InstructorHomeScreen instructorHomeScreen = new InstructorHomeScreen();
        instructorHomeScreen.dispose();
        this.dispose();
        instructorHomeScreen.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RegistrarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarAsistenciaActionPerformed
    API_Admin_BuscarUsuario buscarUsuario = new API_Admin_BuscarUsuario();
    String codigoAprendiz = IngresoCodAprendiz.getText();
    if (codigoAprendiz != null) {
        try {
            JSONObject aprendizData = buscarUsuario.AdminBuscarUsuario(codigoAprendiz);
            System.out.println(aprendizData);
            if (aprendizData != null) {

                boolean yaRegistrado = false;
                for (int i = 0; i < modeloTabla.getRowCount(); i++) {

                    int documento = Integer.parseInt(modeloTabla.getValueAt(i, 3).toString());
                    if (documento == Integer.parseInt(codigoAprendiz)) {
                        yaRegistrado = true;
                        break;
                    }
                }

                if (yaRegistrado) {
                    JOptionPane.showMessageDialog(this, "El aprendiz ya ha sido registrado.");
                    IngresoCodAprendiz.setText("");
                } else {
                    SimpleDateFormat sdf = new SimpleDateFormat("hh:mm a");
                    Date horaActual = sdf.parse(HoraActual());
                    Date horaTardia = sdf.parse(HoraTardia());
                    Date horaInasistencia = sdf.parse(HoraInasistencia());

                    String estado;
                    if (horaActual.before(horaTardia)) {
                        estado = "A tiempo";
                    } else if (horaActual.before(horaInasistencia)) {
                        estado = "Tarde";
                    } else {
                        estado = "Inasistencia";
                    }

                    modeloTabla.addRow(new Object[]{
                            aprendizData.getString("nombres"),
                            aprendizData.getString("apellidos"),
                            aprendizData.getString("tipoDocumento"),
                            aprendizData.getString("documento"),
                            aprendizData.getString("programaFormacion"),
                            aprendizData.getString("nivelFormacion"),
                            Competencia.getText(),
                            HoraActual(),
                            estado
                    });
                    IngresoCodAprendiz.setText("");
                }
            } else {
                int respuesta = JOptionPane.showConfirmDialog(null, "No se han encontrado coincidencias, ¿desea registrar al Aprendiz?", "Confirmación", JOptionPane.YES_NO_CANCEL_OPTION);

                switch (respuesta) {
                    case JOptionPane.YES_OPTION:
                        InstructorRegAprendiz regAprendiz = new InstructorRegAprendiz();
                        regAprendiz.setVisible(true);
                        break;
                    case JOptionPane.NO_OPTION:
                    case JOptionPane.CANCEL_OPTION:
                    case JOptionPane.CLOSED_OPTION:
                        break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la API.");
            e.printStackTrace();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Ingrese el código del aprendiz.");
    }
    }//GEN-LAST:event_RegistrarAsistenciaActionPerformed


    private void FinalizarAsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarAsisActionPerformed
        Workbook workbook = null;

        try {
            ConvertirDatos convertirDatos = new ConvertirDatos();
            Map<String, Object> params = new HashMap<>();
            params.put("Instructor", InstructorNombre.getText());
            params.put("Competencia", Competencia.getText());
            params.put("Ambiente", AmbienteCB.getSelectedItem().toString());
            params.put("Ficha", Integer.valueOf(FichaCB.getSelectedItem().toString()));
            params.put("IDProgramaFormacion", convertirDatos.ObtenerIDProgramaFormacion(ProgramaFormacionCB.getSelectedItem().toString()));
            System.out.println(params);
            workbook = new XSSFWorkbook();
            Sheet sheet = workbook.createSheet("Asistencia");

            // Crear encabezados
            Row headerRow = sheet.createRow(0);
            for (int i = 0; i < modeloTabla.getColumnCount(); i++) {
                Cell cell = headerRow.createCell(i);
                cell.setCellValue(modeloTabla.getColumnName(i));
            }

            // Rellenar filas con los datos de la JTable
            for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                Row row = sheet.createRow(i + 1);
                for (int j = 0; j < modeloTabla.getColumnCount(); j++) {
                    Cell cell = row.createCell(j);
                    cell.setCellValue(modeloTabla.getValueAt(i, j).toString());
                }
            }

            // Crear formato condicional
            SheetConditionalFormatting sheetCF = sheet.getSheetConditionalFormatting();

            // Definir un color verde claro personalizado
            XSSFColor lightGreen = new XSSFColor(new Color(198, 224, 180), null);

            // Definir un naranja personalizado para "Tarde"
            XSSFColor orange = new XSSFColor(new Color(244, 176, 132), null);

            // Definir un rojo personalizado para "Inasistencia"
            XSSFColor red = new XSSFColor(new Color(255, 71, 71), null);

            // Condición para "A tiempo" (verde claro)
            ConditionalFormattingRule ruleAtempo = sheetCF.createConditionalFormattingRule(ComparisonOperator.EQUAL, "\"A tiempo\"");
            PatternFormatting fillAtempo = ruleAtempo.createPatternFormatting();
            ((XSSFPatternFormatting) fillAtempo).setFillBackgroundColor(lightGreen);
            fillAtempo.setFillPattern(PatternFormatting.SOLID_FOREGROUND);

            // Condición para "Tarde" (naranja)
            ConditionalFormattingRule ruleTarde = sheetCF.createConditionalFormattingRule(ComparisonOperator.EQUAL, "\"Tarde\"");
            PatternFormatting fillTarde = ruleTarde.createPatternFormatting();
            ((XSSFPatternFormatting) fillTarde).setFillBackgroundColor(orange);
            fillTarde.setFillPattern(PatternFormatting.SOLID_FOREGROUND);

            // Condición para "Inasistencia" (rojo)
            ConditionalFormattingRule ruleInasistencia = sheetCF.createConditionalFormattingRule(ComparisonOperator.EQUAL, "\"Inasistencia\"");
            PatternFormatting fillInasistencia = ruleInasistencia.createPatternFormatting();
            ((XSSFPatternFormatting) fillInasistencia).setFillBackgroundColor(red);
            fillInasistencia.setFillPattern(PatternFormatting.SOLID_FOREGROUND);

            // Rango de celdas a las que se aplicarán las reglas de formato condicional
            CellRangeAddress[] regions = {
                CellRangeAddress.valueOf("I2:I" + (modeloTabla.getRowCount() + 1)) // Columna "Estado"
            };

            // Aplicar formato condicional usando un array de reglas
            ConditionalFormattingRule[] rules = {ruleAtempo, ruleTarde, ruleInasistencia};
            sheetCF.addConditionalFormatting(regions, rules);
            
            // Guardar el archivo en el sistema
            String filePath = "asistencia.xlsx";
            try (FileOutputStream fileOut = new FileOutputStream(filePath)) {
                workbook.write(fileOut);
            }

            // Enviar el archivo a la API
            File file = new File(filePath);
            UploadFileAPI uploadFileAPI = new UploadFileAPI();
            uploadFileAPI.uploadFileAPI(file, params);

            // Abrir el archivo guardado (opcional)
            if (Desktop.isDesktopSupported() && file.exists()) {
                Desktop.getDesktop().open(file);
            }

            JOptionPane.showMessageDialog(null, "Archivo Excel generado y subido exitosamente.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al generar el archivo Excel.");
            e.printStackTrace();
        } finally {
            if (workbook != null) {
                try {
                    workbook.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_FinalizarAsisActionPerformed

    private void IngresoCodAprendizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoCodAprendizActionPerformed
        RegistrarAsistencia.doClick();
    }//GEN-LAST:event_IngresoCodAprendizActionPerformed

    private void ProgramaFormacionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramaFormacionCBActionPerformed
        if (!ProgramaFormacionCB.getSelectedItem().equals("Seleccionar...") && !ProgramaFormacionCB.getSelectedItem().equals("No aplica")) {
            try {
                ConvertirDatos convertirDatos = new ConvertirDatos();

                // Obtén el ID del programa de formación
                Integer idProgramaFormacion = convertirDatos.ObtenerIDProgramaFormacion(ProgramaFormacionCB.getSelectedItem().toString());

                // Obtén la lista de fichas como enteros
                List<Integer> tiposFichas = convertirDatos.ObtenerFichasPorPrograma(idProgramaFormacion);

                if (tiposFichas == null) {
                    JOptionPane.showMessageDialog(null, "Hubo un error cargando las Fichas de la API");
                } else {
                    // Convierte la lista de enteros a una lista de cadenas
                    List<String> tiposFichasStr = tiposFichas.stream()
                            .map(String::valueOf)
                            .collect(Collectors.toList());

                    // Añade la opción "Seleccionar..." al inicio de la lista
                    tiposFichasStr.add(0, "Seleccionar...");

                    // Convierte la lista de cadenas a un array y configura el modelo del combo box
                    DefaultComboBoxModel<String> FichasBoxModel = new DefaultComboBoxModel<>(tiposFichasStr.toArray(new String[0]));
                    FichaCB.setModel(FichasBoxModel);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            FichaCB.setEnabled(true);
        } else {
            FichaCB.setSelectedItem("Seleccionar...");
            FichaCB.setEnabled(false);
        }
    }//GEN-LAST:event_ProgramaFormacionCBActionPerformed

    private void FichaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FichaCBActionPerformed
        ListarAprendicesModel = ListarUsuarios.getAprendices(Integer.valueOf(FichaCB.getSelectedItem().toString()));
        ListarAprendices.setModel(ListarAprendicesModel);
    }//GEN-LAST:event_FichaCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcelGenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcelGenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcelGenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcelGenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcelGenFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AmbienteCB;
    private javax.swing.JTextField Competencia;
    private javax.swing.JComboBox<String> FichaCB;
    private javax.swing.JButton FinalizarAsis;
    private javax.swing.JLabel HoraFin;
    private javax.swing.JLabel HoraInicio;
    private javax.swing.JTextField IngresoCodAprendiz;
    private javax.swing.JLabel InstructorNombre;
    private javax.swing.JTable ListarAprendices;
    private javax.swing.JComboBox<String> ProgramaFormacionCB;
    private javax.swing.JButton RegistrarAsistencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaAsis;
    // End of variables declaration//GEN-END:variables
}


