/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.AdminFrames.AdminActionScreens.CreateUserSubPanel;

import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Map;

import main.util.API_AdminActions.API_Admin_UsersApplications.API_Admin_AprendizApplications;
import main.util.models.ComboBoxModels;

import javax.swing.*;

import main.util.models.DataTables;
import main.util.models.UsersModels.AprendizModel;

/**
 *
 * @author usuario
 */
public class CreateAprendizSubPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAprendizSubPanel
     */

    DefaultComboBoxModel<String> yearModel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> mesModel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> diaModel = new DefaultComboBoxModel<>();
    public CreateAprendizSubPanel() {
        initComponents();
        aditionalConfig();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateAprendizSubPanel = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        RegistrarUsuario = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        RegistrarNombres = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        RegistrarArea = new javax.swing.JTextField();
        RegistrarCorreo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        RegistrarApellidos = new javax.swing.JTextField();
        RegistrarDocumento = new javax.swing.JTextField();
        FichaCB = new javax.swing.JComboBox<>();
        RegistrarTelefono = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TipoDocCB = new javax.swing.JComboBox<>();
        GeneroCB = new javax.swing.JComboBox<>();
        RegistrarNivelFormacion = new javax.swing.JTextField();
        RegistrarSede = new javax.swing.JTextField();
        RegistrarJornadaFormacion = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        DepartamentoCB = new javax.swing.JComboBox<>();
        BarrioCB = new javax.swing.JComboBox<>();
        MunicipioCB = new javax.swing.JComboBox<>();
        ConfirmarRegistroUsuario = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        RegistrarProgramaFormacion = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        YearCB = new javax.swing.JComboBox<>();
        MesCB = new javax.swing.JComboBox<>();
        DiaCB = new javax.swing.JComboBox<>();
        FechaHolder = new javax.swing.JTextField();
        ResidenciaHolder = new javax.swing.JTextField();
        RegistrarPass = new javax.swing.JPasswordField();
        RefrescarCombos = new javax.swing.JButton();

        CreateAprendizSubPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Usuario");

        RegistrarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RegistrarUsuario.setForeground(new java.awt.Color(0, 0, 0));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Contraseña");

        RegistrarNombres.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RegistrarNombres.setForeground(new java.awt.Color(0, 0, 0));
        RegistrarNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RegistrarNombresKeyTyped(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Correo");

        RegistrarArea.setEditable(false);
        RegistrarArea.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RegistrarArea.setForeground(new java.awt.Color(0, 0, 0));
        RegistrarArea.setFocusable(false);

        RegistrarCorreo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RegistrarCorreo.setForeground(new java.awt.Color(0, 0, 0));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Documento");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Numero de ficha");

        RegistrarApellidos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RegistrarApellidos.setForeground(new java.awt.Color(0, 0, 0));
        RegistrarApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RegistrarApellidosKeyTyped(evt);
            }
        });

        RegistrarDocumento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RegistrarDocumento.setForeground(new java.awt.Color(0, 0, 0));
        RegistrarDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RegistrarDocumentoKeyTyped(evt);
            }
        });

        FichaCB.setForeground(new java.awt.Color(0, 0, 0));
        FichaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        FichaCB.setPreferredSize(new java.awt.Dimension(64, 28));
        FichaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FichaCBActionPerformed(evt);
            }
        });

        RegistrarTelefono.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RegistrarTelefono.setForeground(new java.awt.Color(0, 0, 0));
        RegistrarTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RegistrarTelefonoKeyTyped(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Jornada de formacion");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Telefono");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Area de trabajo");

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Nivel de formacion");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Nombres");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Apellidos");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Tipo de documento");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Genero");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Sede");

        TipoDocCB.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TipoDocCB.setForeground(new java.awt.Color(0, 0, 0));
        TipoDocCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TipoDocCB.setPreferredSize(new java.awt.Dimension(64, 28));
        TipoDocCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDocCBActionPerformed(evt);
            }
        });

        GeneroCB.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        GeneroCB.setForeground(new java.awt.Color(0, 0, 0));
        GeneroCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        GeneroCB.setPreferredSize(new java.awt.Dimension(64, 28));
        GeneroCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroCBActionPerformed(evt);
            }
        });

        RegistrarNivelFormacion.setEditable(false);
        RegistrarNivelFormacion.setFocusable(false);

        RegistrarSede.setEditable(false);
        RegistrarSede.setFocusable(false);

        RegistrarJornadaFormacion.setEditable(false);
        RegistrarJornadaFormacion.setFocusable(false);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Residencia");

        DepartamentoCB.setForeground(new java.awt.Color(0, 0, 0));
        DepartamentoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DepartamentoCB.setPreferredSize(new java.awt.Dimension(64, 28));
        DepartamentoCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartamentoCBActionPerformed(evt);
            }
        });

        BarrioCB.setForeground(new java.awt.Color(0, 0, 0));
        BarrioCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BarrioCB.setEnabled(false);
        BarrioCB.setPreferredSize(new java.awt.Dimension(64, 28));
        BarrioCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarrioCBActionPerformed(evt);
            }
        });

        MunicipioCB.setForeground(new java.awt.Color(0, 0, 0));
        MunicipioCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MunicipioCB.setEnabled(false);
        MunicipioCB.setPreferredSize(new java.awt.Dimension(64, 28));
        MunicipioCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MunicipioCBActionPerformed(evt);
            }
        });

        ConfirmarRegistroUsuario.setBackground(new java.awt.Color(0, 34, 64));
        ConfirmarRegistroUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmarRegistroUsuario.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmarRegistroUsuario.setText("Crear nuevo Aprendiz");
        ConfirmarRegistroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarRegistroUsuarioActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Programa de Formacion");

        RegistrarProgramaFormacion.setEditable(false);
        RegistrarProgramaFormacion.setFocusable(false);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Fecha de Nacimiento");

        YearCB.setForeground(new java.awt.Color(0, 0, 0));
        YearCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        YearCB.setPreferredSize(new java.awt.Dimension(64, 28));
        YearCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearCBActionPerformed(evt);
            }
        });

        MesCB.setForeground(new java.awt.Color(0, 0, 0));
        MesCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MesCB.setEnabled(false);
        MesCB.setPreferredSize(new java.awt.Dimension(64, 28));
        MesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesCBActionPerformed(evt);
            }
        });

        DiaCB.setForeground(new java.awt.Color(0, 0, 0));
        DiaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DiaCB.setEnabled(false);
        DiaCB.setPreferredSize(new java.awt.Dimension(64, 28));
        DiaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaCBActionPerformed(evt);
            }
        });

        FechaHolder.setEditable(false);
        FechaHolder.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        FechaHolder.setForeground(new java.awt.Color(0, 0, 0));
        FechaHolder.setFocusable(false);

        ResidenciaHolder.setEditable(false);
        ResidenciaHolder.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResidenciaHolder.setForeground(new java.awt.Color(0, 0, 0));
        ResidenciaHolder.setFocusable(false);

        RegistrarPass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        RefrescarCombos.setBackground(new java.awt.Color(57, 169, 0));
        RefrescarCombos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RefrescarCombos.setForeground(new java.awt.Color(255, 255, 255));
        RefrescarCombos.setText("Refrescar comboBox");
        RefrescarCombos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefrescarCombosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreateAprendizSubPanelLayout = new javax.swing.GroupLayout(CreateAprendizSubPanel);
        CreateAprendizSubPanel.setLayout(CreateAprendizSubPanelLayout);
        CreateAprendizSubPanelLayout.setHorizontalGroup(
            CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateAprendizSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateAprendizSubPanelLayout.createSequentialGroup()
                        .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CreateAprendizSubPanelLayout.createSequentialGroup()
                                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel19))
                                .addGap(67, 67, 67)
                                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(RegistrarNombres, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegistrarPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
                                    .addComponent(RegistrarUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegistrarApellidos)
                                    .addComponent(TipoDocCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RegistrarDocumento, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CreateAprendizSubPanelLayout.createSequentialGroup()
                                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel25))
                                .addGap(56, 56, 56)
                                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CreateAprendizSubPanelLayout.createSequentialGroup()
                                        .addComponent(DepartamentoCB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MunicipioCB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BarrioCB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ResidenciaHolder, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
                                    .addComponent(RegistrarCorreo)
                                    .addComponent(RegistrarTelefono)
                                    .addComponent(GeneroCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(CreateAprendizSubPanelLayout.createSequentialGroup()
                                        .addComponent(YearCB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MesCB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DiaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FechaHolder))
                                    .addComponent(FichaCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(6, 6, 6))
                    .addGroup(CreateAprendizSubPanelLayout.createSequentialGroup()
                        .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ConfirmarRegistroUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CreateAprendizSubPanelLayout.createSequentialGroup()
                                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel17))
                                .addGap(33, 33, 33)
                                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RegistrarArea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
                                    .addComponent(RegistrarJornadaFormacion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegistrarNivelFormacion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegistrarSede)
                                    .addComponent(RegistrarProgramaFormacion, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateAprendizSubPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RefrescarCombos, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CreateAprendizSubPanelLayout.setVerticalGroup(
            CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateAprendizSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RefrescarCombos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CreateAprendizSubPanelLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addGap(6, 6, 6))
                    .addGroup(CreateAprendizSubPanelLayout.createSequentialGroup()
                        .addComponent(RegistrarPass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RegistrarDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoDocCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel25)
                        .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(YearCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MesCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DiaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(FechaHolder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GeneroCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(RegistrarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DepartamentoCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MunicipioCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BarrioCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ResidenciaHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(FichaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(RegistrarProgramaFormacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarNivelFormacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(6, 6, 6)
                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarJornadaFormacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(RegistrarArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateAprendizSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(RegistrarSede, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmarRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateAprendizSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateAprendizSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TipoDocCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDocCBActionPerformed

    }//GEN-LAST:event_TipoDocCBActionPerformed

    private void GeneroCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroCBActionPerformed

    private void FichaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FichaCBActionPerformed
           String fichaSeleccionada = (String) FichaCB.getSelectedItem();

            if (fichaSeleccionada != null && !fichaSeleccionada.equals("Seleccionar...")) {
                try {
                    // Convertir el valor seleccionado a un número de ficha (si corresponde)
                    int ficha = Integer.parseInt(fichaSeleccionada);
                    System.out.println(ficha);

                    // Crear una instancia de DataTables para realizar la consulta
                    DataTables dataTables = new DataTables();

                    // Consultar el programa de formación por la ficha seleccionada
                    Map<String, Object> FichaDataResult = dataTables.obtenerProgramaFormacionPorFicha(ficha);
                    System.out.println(FichaDataResult);

                    if (FichaDataResult != null) {
                        // Colocar el valor obtenido en el JTextField correspondiente
                        RegistrarProgramaFormacion.setText((String) FichaDataResult.get("ProgramaFormacion"));
                        RegistrarNivelFormacion.setText((String) FichaDataResult.get("NivelFormacion"));
                        RegistrarJornadaFormacion.setText((String) FichaDataResult.get("JornadasFormacion"));
                        RegistrarSede.setText((String) FichaDataResult.get("Sede"));
                        RegistrarArea.setText((String) FichaDataResult.get("Area"));

                    } else {
                        // Si no se obtiene un resultado válido, limpiar el campo de texto
                        RegistrarProgramaFormacion.setText((String) FichaDataResult.get("ProgramaFormacion No encontrado"));
                        RegistrarNivelFormacion.setText((String) FichaDataResult.get("NivelFormacion No encontrado"));
                        RegistrarJornadaFormacion.setText((String) FichaDataResult.get("JornadasFormacion No encontrado"));
                        RegistrarSede.setText((String) FichaDataResult.get("Sede No encontrado"));
                        RegistrarArea.setText((String) FichaDataResult.get("Area No encontrado"));
                    }
                } catch (NumberFormatException ex) {
                    ex.printStackTrace();
                        RegistrarProgramaFormacion.setText("ProgramaFormacion Invalida");
                        RegistrarNivelFormacion.setText("NivelFormacion Invalida");
                        RegistrarJornadaFormacion.setText("JornadasFormacion Invalida");
                        RegistrarSede.setText("Sede Invalida");
                        RegistrarArea.setText("Area Invalida");
                }
            } else {
                // Limpiar el campo si no hay selección válida
                        RegistrarProgramaFormacion.setText("");
                        RegistrarNivelFormacion.setText("");
                        RegistrarJornadaFormacion.setText("");
                        RegistrarSede.setText("");
                        RegistrarArea.setText("");
            }
    }//GEN-LAST:event_FichaCBActionPerformed

    public void aditionalConfig(){
        yearModel.addElement("Seleccionar Año");
        llenarYear(yearModel);
        mesModel.addElement("Seleccionar Mes");
        diaModel.addElement("Seleccionar Día");
        try {
            ComboBoxModels CBModels = new ComboBoxModels();
            TipoDocCB.setModel(CBModels.generarComboBoxModelPorTipo("TipoDocumento"));
            GeneroCB.setModel(CBModels.generarComboBoxModelPorTipo("Genero"));
            MunicipioCB.setModel(CBModels.generarComboBoxModelPorTipo("Municipios"));
            DepartamentoCB.setModel(CBModels.generarComboBoxModelPorTipo("Departamentos"));
            BarrioCB.setModel(CBModels.generarComboBoxModelPorTipo("Barrios"));
            FichaCB.setModel(CBModels.generarComboBoxModelPorTipo("Fichas"));
            YearCB.setModel(yearModel);
            MesCB.setModel(mesModel);
            DiaCB.setModel(diaModel);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    private void llenarYear(DefaultComboBoxModel<String> anhoModel) {
        int anhoActual = Calendar.getInstance().get(Calendar.YEAR);
        for (int i = anhoActual; i > anhoActual - 100; i--) {
            anhoModel.addElement(String.valueOf(i));
        }
    }

    public void llenarMeses() {
        mesModel.removeAllElements();
        mesModel.addElement("Seleccionar Mes");
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
                "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        for (String mes : meses) {
            mesModel.addElement(mes);
        }
    }

    private void llenarDias(DefaultComboBoxModel<String> diaModel, int anho, int mes) {
        diaModel.removeAllElements();
        diaModel.addElement("Seleccionar Día");
        int diasEnMes = obtenerDiasDelMes(anho, mes);
        for (int i = 1; i <= diasEnMes; i++) {
            diaModel.addElement(String.valueOf(i));
        }
    }

    private int obtenerDiasDelMes(int anho, int mes) {
        switch (mes) {
            case 1: case 3: case 5: case 7: case 8: case 10: case 12:
                return 31;
            case 4: case 6: case 9: case 11:
                return 30;
            case 2:
                return (anho % 4 == 0 && (anho % 100 != 0 || anho % 400 == 0)) ? 29 : 28;
            default:
                return 30;
        }
    }

    private int obtenerNumeroMes(String mesSeleccionado) {
        switch (mesSeleccionado) {
            case "Enero": return 1;
            case "Febrero": return 2;
            case "Marzo": return 3;
            case "Abril": return 4;
            case "Mayo": return 5;
            case "Junio": return 6;
            case "Julio": return 7;
            case "Agosto": return 8;
            case "Septiembre": return 9;
            case "Octubre": return 10;
            case "Noviembre": return 11;
            case "Diciembre": return 12;
            default: return -1; // En caso de error
        }
    }

    private void actualizarFecha() {
        String anhoSeleccionado = (String) YearCB.getSelectedItem();
        String mesSeleccionado = (String) MesCB.getSelectedItem();
        String diaSeleccionado = (String) DiaCB.getSelectedItem();

        // Comprobar si los tres elementos han sido seleccionados correctamente
        if (anhoSeleccionado != null && !anhoSeleccionado.equals("Seleccionar Año") &&
                mesSeleccionado != null && !mesSeleccionado.equals("Seleccionar Mes") &&
                diaSeleccionado != null && !diaSeleccionado.equals("Seleccionar Día")) {

            // Convertir el nombre del mes a su número usando obtenerNumeroMes()
            int numeroMes = obtenerNumeroMes(mesSeleccionado);
            String mesConFormato = (numeroMes < 10 ? "0" : "") + numeroMes; // Formatear el mes con cero si es necesario
            String diaConFormato = (Integer.parseInt(diaSeleccionado) < 10 ? "0" : "") + diaSeleccionado; // Formatear el día con cero si es necesario

            // Mostrar la fecha en formato "yyyy-MM-dd"
            FechaHolder.setText(anhoSeleccionado + "-" + mesConFormato + "-" + diaConFormato);
        } else {
            // Si alguno no está seleccionado, mostrar el campo vacío o parcialmente seleccionado
            String fechaParcial = "";
            if (anhoSeleccionado != null && !anhoSeleccionado.equals("Seleccionar Año")) {
                fechaParcial += anhoSeleccionado;
            }
            if (mesSeleccionado != null && !mesSeleccionado.equals("Seleccionar Mes")) {
                int numeroMes = obtenerNumeroMes(mesSeleccionado);
                String mesConFormato = (numeroMes < 10 ? "0" : "") + numeroMes; // Formatear el mes con cero si es necesario
                if (!fechaParcial.isEmpty()) {
                    fechaParcial += "-";  // Solo añadir el guion si ya hay algo en la fecha parcial
                }
                fechaParcial += mesConFormato;
            }
            if (diaSeleccionado != null && !diaSeleccionado.equals("Seleccionar Día")) {
                String diaConFormato = (Integer.parseInt(diaSeleccionado) < 10 ? "0" : "") + diaSeleccionado; // Formatear el día con cero si es necesario
                if (!fechaParcial.isEmpty()) {
                    fechaParcial += "-";  // Solo añadir el guion si ya hay algo en la fecha parcial
                }
                fechaParcial += diaConFormato;
            }
            FechaHolder.setText(fechaParcial); // Mostrar la selección parcial
        }
    }
    
    private void actualizarResidencia() {
        String departamentoSeleccionado = (String) DepartamentoCB.getSelectedItem();
        String municipioSeleccionado = (String) MunicipioCB.getSelectedItem();
        String barrioSeleccionado = (String) BarrioCB.getSelectedItem();

        // Comprobar si los tres elementos han sido seleccionados correctamente
        if (departamentoSeleccionado != null && !departamentoSeleccionado.equals("Seleccionar...") &&
            municipioSeleccionado != null && !municipioSeleccionado.equals("Seleccionar...") &&
            barrioSeleccionado != null && !barrioSeleccionado.equals("Seleccionar...")) {

            // Mostrar la residencia en formato "Departamento - Municipio - Barrio"
            ResidenciaHolder.setText(departamentoSeleccionado + " - " + municipioSeleccionado + " - " + barrioSeleccionado);
        } else {
            // Si alguno no está seleccionado, mostrar el campo parcial
            String residenciaParcial = "";
            if (departamentoSeleccionado != null && !departamentoSeleccionado.equals("Seleccionar...")) {
                residenciaParcial += departamentoSeleccionado;
            }
            if (municipioSeleccionado != null && !municipioSeleccionado.equals("Seleccionar...")) {
                if (!residenciaParcial.isEmpty()) {
                    residenciaParcial += " - ";  // Solo añadir el separador si hay un valor previo
                }
                residenciaParcial += municipioSeleccionado;
            }
            if (barrioSeleccionado != null && !barrioSeleccionado.equals("Seleccionar...")) {
                if (!residenciaParcial.isEmpty()) {
                    residenciaParcial += " - ";  // Solo añadir el separador si hay un valor previo
                }
                residenciaParcial += barrioSeleccionado;
            }
            ResidenciaHolder.setText(residenciaParcial);  // Mostrar la selección parcial
        }
    }

    
    private void DepartamentoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartamentoCBActionPerformed
        String departamentoSeleccionado = (String) DepartamentoCB.getSelectedItem();

        if (departamentoSeleccionado != null && !departamentoSeleccionado.equals("Seleccionar...")) {
            MunicipioCB.setEnabled(true);  // Habilitar el ComboBox de Municipio
            BarrioCB.setEnabled(false);    // Deshabilitar el ComboBox de Barrio hasta que se seleccione un municipio
            BarrioCB.setSelectedItem("Seleccionar...");  // Situar el Barrio en "Seleccionar..."
        } else {
            // Si no se ha seleccionado un departamento válido, deshabilitar Municipio y Barrio
            MunicipioCB.setEnabled(false);
            BarrioCB.setEnabled(false);
            MunicipioCB.setSelectedItem("Seleccionar...");  // Situar el Municipio en "Seleccionar..."
            BarrioCB.setSelectedItem("Seleccionar...");     // Situar el Barrio en "Seleccionar..."
        }

        actualizarResidencia();  // Actualizar el ResidenciaHolder
    }//GEN-LAST:event_DepartamentoCBActionPerformed

    private void BarrioCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarrioCBActionPerformed
        actualizarResidencia();  // Llamar al método para actualizar el ResidenciaHolder
    }//GEN-LAST:event_BarrioCBActionPerformed

    private void MunicipioCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MunicipioCBActionPerformed
        String municipioSeleccionado = (String) MunicipioCB.getSelectedItem();

        if (municipioSeleccionado != null && !municipioSeleccionado.equals("Seleccionar...")) {
            BarrioCB.setEnabled(true);  // Habilitar el ComboBox de Barrio
        } else {
            BarrioCB.setEnabled(false);  // Deshabilitar el ComboBox de Barrio si no se selecciona un municipio válido
            BarrioCB.setSelectedItem("Seleccionar...");   // Situar el Barrio en "Seleccionar..."
        }

        actualizarResidencia();  // Actualizar el ResidenciaHolder
    }//GEN-LAST:event_MunicipioCBActionPerformed

    private void ConfirmarRegistroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarRegistroUsuarioActionPerformed
// Formato de la fecha esperada
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        formatoFecha.setLenient(false); // Validación estricta de la fecha
        java.util.Date fechaNacimientoUtil = null;
        java.sql.Date fechaNacimiento = null;

        // Variable para acumular errores de validación
        StringBuilder errores = new StringBuilder();

        // 1. Validación de Campos Obligatorios
        if (RegistrarUsuario.getText().trim().isEmpty()) {
            errores.append("- El campo de Usuario es obligatorio.\n");
        }

        if (RegistrarPass.getText().trim().isEmpty()) {
            errores.append("- El campo de Contraseña es obligatorio.\n");
        }

        if (RegistrarDocumento.getText().trim().isEmpty()) {
            errores.append("- El campo de Documento es obligatorio.\n");
        }

        if (RegistrarNombres.getText().trim().isEmpty()) {
            errores.append("- El campo de Nombres es obligatorio.\n");
        }

        if (RegistrarApellidos.getText().trim().isEmpty()) {
            errores.append("- El campo de Apellidos es obligatorio.\n");
        }

        if (FechaHolder.getText().trim().isEmpty()) {
            errores.append("- El campo de Fecha de Nacimiento es obligatorio.\n");
        }

        if (RegistrarTelefono.getText().trim().isEmpty()) {
            errores.append("- El campo de Teléfono es obligatorio.\n");
        }

        if (RegistrarCorreo.getText().trim().isEmpty()) {
            errores.append("- El campo de Correo Electrónico es obligatorio.\n");
        }

        if (ResidenciaHolder.getText().trim().isEmpty()) {
            errores.append("- El campo de Residencia es obligatorio.\n");
        }

        if (FichaCB.getSelectedItem() == null) {
            errores.append("- Debes seleccionar una Ficha.\n");
        }

        if (RegistrarProgramaFormacion.getText().trim().isEmpty()) {
            errores.append("- El campo de Programa de Formación es obligatorio.\n");
        }

        if (RegistrarNivelFormacion.getText().trim().isEmpty()) {
            errores.append("- El campo de Nivel de Formación es obligatorio.\n");
        }

        if (RegistrarJornadaFormacion.getText().trim().isEmpty()) {
            errores.append("- El campo de Jornada de Formación es obligatorio.\n");
        }

        if (RegistrarArea.getText().trim().isEmpty()) {
            errores.append("- El campo de Área es obligatorio.\n");
        }

        if (RegistrarSede.getText().trim().isEmpty()) {
            errores.append("- El campo de Sede es obligatorio.\n");
        }

        // 2. Validación de Fecha de Nacimiento
        if (!FechaHolder.getText().trim().isEmpty()) {
            try {
                String fechaTexto = FechaHolder.getText().trim();
                fechaNacimientoUtil = formatoFecha.parse(fechaTexto);
                fechaNacimiento = new java.sql.Date(fechaNacimientoUtil.getTime());

                // Verificar que la fecha no sea futura ni demasiado antigua
                if (fechaNacimiento.before(java.sql.Date.valueOf("1900-01-01")) || fechaNacimiento.after(new java.sql.Date(System.currentTimeMillis()))) {
                    errores.append("- La Fecha de Nacimiento es inválida.\n");
                }

            } catch (ParseException e) {
                errores.append("- La Fecha de Nacimiento debe tener el formato 'yyyy-MM-dd'.\n");
            }
        }

        // 3. Validación de Correo Electrónico con Expresión Regular
        if (!RegistrarCorreo.getText().trim().isEmpty()) {
            String correo = RegistrarCorreo.getText().trim();
            String regexCorreo = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
            if (!correo.matches(regexCorreo)) {
                errores.append("- El Correo Electrónico no es válido.\n");
            }
        }

        // 4. Validación de Teléfono (solo números y longitud mínima)
        if (!RegistrarTelefono.getText().trim().isEmpty()) {
            String telefono = RegistrarTelefono.getText().trim();
            String regexTelefono = "^[0-9]{7,15}$"; // Ajusta la longitud según sea necesario
            if (!telefono.matches(regexTelefono)) {
                errores.append("- El Teléfono debe contener solo números y tener entre 7 y 15 dígitos.\n");
            }
        }

        // 5. Validación de Documento (solo números y mínimo 4 caracteres)
        if (!RegistrarDocumento.getText().trim().isEmpty()) {
            String documento = RegistrarDocumento.getText().trim();
            if (!documento.matches("^[0-9]{4,}$")) { // Solo números y al menos 4 dígitos
                errores.append("- El Documento debe contener solo números y tener al menos 4 dígitos.\n");
            }
        }

        // 6. Validación de Contraseña (mínimo 8 caracteres)
        if (!RegistrarPass.getText().trim().isEmpty()) {
            String contraseña = RegistrarPass.getText().trim();
            if (contraseña.length() < 8) {
                errores.append("- La Contraseña debe tener al menos 8 caracteres.\n");
            }
            // Puedes agregar más validaciones si es necesario, como combinaciones de letras y números
        }

        // 7. Validación de Ficha (convertir a entero)
        Integer ficha = null;
        if (FichaCB.getSelectedItem() != null) {
            try {
                ficha = Integer.parseInt(FichaCB.getSelectedItem().toString());
            } catch (NumberFormatException e) {
                errores.append("- La Ficha seleccionada no es válida.\n");
            }
        }
// Crear el objeto AprendizModel con la fecha convertida a Date
        AprendizModel aprendiz = new AprendizModel(
                RegistrarUsuario.getText(),
                RegistrarPass.getText(),
                RegistrarDocumento.getText(),
                TipoDocCB.getSelectedItem().toString(),
                RegistrarNombres.getText(),
                RegistrarApellidos.getText(),
                fechaNacimiento,  // Pasa el objeto Date aquí
                RegistrarTelefono.getText(),
                RegistrarCorreo.getText(),
                GeneroCB.getSelectedItem().toString(),
                ResidenciaHolder.getText(),
                FichaCB.getSelectedItem() != null ? Integer.parseInt(FichaCB.getSelectedItem().toString()) : null,
                RegistrarProgramaFormacion.getText(),
                RegistrarNivelFormacion.getText(),
                RegistrarJornadaFormacion.getText(),
                RegistrarArea.getText(),
                RegistrarSede.getText()
        );

        API_Admin_AprendizApplications createAprendiz = new API_Admin_AprendizApplications();
        createAprendiz.CrearAprendiz(aprendiz);
        JOptionPane.showMessageDialog(null, "Aprendiz registrado exitosamente");

        limpiarFormularioAprendiz();

    }//GEN-LAST:event_ConfirmarRegistroUsuarioActionPerformed

    private void limpiarFormularioAprendiz() {
        // Limpiar JTextFields
        RegistrarUsuario.setText("");
        RegistrarPass.setText("");
        RegistrarDocumento.setText("");
        RegistrarNombres.setText("");
        RegistrarApellidos.setText("");
        RegistrarTelefono.setText("");
        RegistrarCorreo.setText("");
        ResidenciaHolder.setText("");
        FechaHolder.setText("");
        RegistrarProgramaFormacion.setText("");
        RegistrarNivelFormacion.setText("");
        RegistrarJornadaFormacion.setText("");
        RegistrarArea.setText("");
        RegistrarSede.setText("");

        // Restablecer JComboBoxes
        TipoDocCB.setSelectedIndex(0);  // Asumiendo que el índice 0 es "Seleccionar..."
        YearCB.setSelectedIndex(0);
        MesCB.setSelectedIndex(0);
        MesCB.setEnabled(false);
        DiaCB.setSelectedIndex(0);
        DiaCB.setEnabled(false);
        GeneroCB.setSelectedIndex(0);  // Asumiendo que el índice 0 es "Seleccionar..."
        DepartamentoCB.setSelectedIndex(0);
        MunicipioCB.setSelectedIndex(0);
        MunicipioCB.setEnabled(false);
        BarrioCB.setSelectedIndex(0);
        BarrioCB.setEnabled(false);
        FichaCB.setSelectedIndex(0);
        // Si tienes alguna tabla o componente adicional en Aprendiz, también debes limpiarlo
    }

    private void YearCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearCBActionPerformed
        String YearSeleccionado = (String) YearCB.getSelectedItem();

        // Verificamos si es "Seleccionar Año"
        if (YearSeleccionado == null || YearSeleccionado.equals("Seleccionar Año")) {
            mesModel.removeAllElements();   // Limpiar los meses
            mesModel.addElement("Seleccionar Mes");  // Volver a poner la opción por defecto
            MesCB.setEnabled(false);  // Deshabilitar el ComboBox de Mes

            diaModel.removeAllElements();   // Limpiar los días
            diaModel.addElement("Seleccionar Día");  // Volver a poner la opción por defecto
            DiaCB.setEnabled(false);  // Deshabilitar el ComboBox de Día
        } else {
            // Si se selecciona un año válido, llenar los meses
            llenarMeses();  // Llenar los meses
            MesCB.setEnabled(true);  // Habilitar el ComboBox de Mes
            DiaCB.setEnabled(false); // Deshabilitar el ComboBox de Día hasta que se seleccione un mes
            DiaCB.removeAllItems();  // Limpiar los días por si acaso
        }

        actualizarFecha();  // Actualizar el TextField FechaHolder
    }//GEN-LAST:event_YearCBActionPerformed

    private void MesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesCBActionPerformed
        String mesSeleccionado = (String) MesCB.getSelectedItem();

        // Verificamos si es "Seleccionar Mes"
        if (mesSeleccionado == null || mesSeleccionado.equals("Seleccionar Mes")) {
            diaModel.removeAllElements();   // Limpiar los días
            diaModel.addElement("Seleccionar Día");  // Volver a poner la opción por defecto
            DiaCB.setEnabled(false);  // Deshabilitar el ComboBox de Día
        } else {
            // Si se selecciona un mes válido, llenar los días
            int anho = Integer.parseInt((String) YearCB.getSelectedItem());
            int numeroMes = obtenerNumeroMes(mesSeleccionado);  // Obtener el número correcto del mes

            // Llenar los días en el ComboBox de Día
            llenarDias(diaModel, anho, numeroMes);
            DiaCB.setEnabled(true);  // Habilitar el ComboBox de Día
        }

        actualizarFecha();  // Actualizar el TextField FechaHolder
    }//GEN-LAST:event_MesCBActionPerformed

    private void DiaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaCBActionPerformed
        String diaSeleccionado = (String) DiaCB.getSelectedItem();

        if (diaSeleccionado != null && !diaSeleccionado.equals("Seleccionar Día")) {
            actualizarFecha();  // Llamada al método para actualizar el TextField
        }
    }//GEN-LAST:event_DiaCBActionPerformed

    private void RegistrarTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RegistrarTelefonoKeyTyped
        char caracter = evt.getKeyChar();

        // Permitir solo números y la tecla de retroceso
        if (!Character.isDigit(caracter) && caracter != KeyEvent.VK_BACK_SPACE) {
            evt.consume();  // Evitar que se ingrese el carácter no válido
            JOptionPane.showMessageDialog(this, "Solo se permiten números.");
        }
    }//GEN-LAST:event_RegistrarTelefonoKeyTyped

    private void RegistrarDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RegistrarDocumentoKeyTyped
        char caracter = evt.getKeyChar();

        // Permitir solo números y la tecla de retroceso
        if (!Character.isDigit(caracter) && caracter != KeyEvent.VK_BACK_SPACE) {
            evt.consume();  // Evitar que se ingrese el carácter no válido
            JOptionPane.showMessageDialog(this, "Solo se permiten números.");
        }
    }//GEN-LAST:event_RegistrarDocumentoKeyTyped

    private void RegistrarNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RegistrarNombresKeyTyped
        char caracter = evt.getKeyChar();

        // Permitir solo letras, la barra espaciadora y las teclas de control (como backspace)
        if (!Character.isLetter(caracter) && caracter != '\b' && caracter != ' ') {
            evt.consume();  // Evitar que se ingrese el carácter no válido
            JOptionPane.showMessageDialog(this, "Solo se permiten letras y espacios.");
        }
    }//GEN-LAST:event_RegistrarNombresKeyTyped

    private void RegistrarApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RegistrarApellidosKeyTyped
        char caracter = evt.getKeyChar();

        // Permitir solo letras, la barra espaciadora y las teclas de control (como backspace)
        if (!Character.isLetter(caracter) && caracter != '\b' && caracter != ' ') {
            evt.consume();  // Evitar que se ingrese el carácter no válido
            JOptionPane.showMessageDialog(this, "Solo se permiten letras y espacios.");
        }
    }//GEN-LAST:event_RegistrarApellidosKeyTyped

    private void RefrescarCombosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefrescarCombosActionPerformed
        refrescarComboBoxes();
    }//GEN-LAST:event_RefrescarCombosActionPerformed

    public void refrescarComboBoxes() {
        try {
            ComboBoxModels cbm = new ComboBoxModels();
            // Actualizar los ComboBox con los modelos más recientes
            ComboBoxModels CBModels = new ComboBoxModels();
            TipoDocCB.setModel(CBModels.generarComboBoxModelPorTipo("TipoDocumento"));
            GeneroCB.setModel(CBModels.generarComboBoxModelPorTipo("Genero"));
            MunicipioCB.setModel(CBModels.generarComboBoxModelPorTipo("Municipios"));
            DepartamentoCB.setModel(CBModels.generarComboBoxModelPorTipo("Departamentos"));
            BarrioCB.setModel(CBModels.generarComboBoxModelPorTipo("Barrios"));
            FichaCB.setModel(CBModels.generarComboBoxModelPorTipo("Fichas"));
            YearCB.setModel(yearModel);
            MesCB.setModel(mesModel);
            DiaCB.setModel(diaModel);

            JOptionPane.showMessageDialog(this, "Los ComboBox han sido actualizados correctamente.", "ComboBox Actualizados", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al refrescar los ComboBox: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BarrioCB;
    private javax.swing.JButton ConfirmarRegistroUsuario;
    private javax.swing.JPanel CreateAprendizSubPanel;
    private javax.swing.JComboBox<String> DepartamentoCB;
    private javax.swing.JComboBox<String> DiaCB;
    private javax.swing.JTextField FechaHolder;
    private javax.swing.JComboBox<String> FichaCB;
    private javax.swing.JComboBox<String> GeneroCB;
    private javax.swing.JComboBox<String> MesCB;
    private javax.swing.JComboBox<String> MunicipioCB;
    private javax.swing.JButton RefrescarCombos;
    private javax.swing.JTextField RegistrarApellidos;
    private javax.swing.JTextField RegistrarArea;
    private javax.swing.JTextField RegistrarCorreo;
    private javax.swing.JTextField RegistrarDocumento;
    private javax.swing.JTextField RegistrarJornadaFormacion;
    private javax.swing.JTextField RegistrarNivelFormacion;
    private javax.swing.JTextField RegistrarNombres;
    private javax.swing.JPasswordField RegistrarPass;
    private javax.swing.JTextField RegistrarProgramaFormacion;
    private javax.swing.JTextField RegistrarSede;
    private javax.swing.JTextField RegistrarTelefono;
    private javax.swing.JTextField RegistrarUsuario;
    private javax.swing.JTextField ResidenciaHolder;
    private javax.swing.JComboBox<String> TipoDocCB;
    private javax.swing.JComboBox<String> YearCB;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    // End of variables declaration//GEN-END:variables
}
