/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.InstructorFrames;

import main.util.API_AdminActions.API_Admin_UsersApplications.API_Admin_AprendizApplications;
import main.util.models.ComboBoxModels;
import main.util.models.DataTables;
import main.util.models.UsersModels.AprendizModel;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 *
 * @author usuario
 */
public class InstructorApList extends JPanel {

    /**
     * Creates new form InstructorApList
     */
    private DefaultTableModel ListarApModel;

    public InstructorApList() {

        initComponents();
        aditionalConfig();
    }

    public void aditionalConfig(){

        ListarApModel = new DefaultTableModel(new Object[]{
                "Documento", "Tipo Documento", "Nombres", "Fecha Nacimiento",
                "Telefono", "Correo", "Genero", "Residencia", "Ficha",
                "Programa Formacion", "Jornada Formacion",
                "Nivel Formacion", "Sede", "Area"}, 0);

        ListaAprendicesFichaTable.setModel(ListarApModel);
        ComboBoxModels cbm = new ComboBoxModels();
        FichasAsociadasCB.setModel(cbm.generarComboBoxModelPorTipo("Fichas"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        FichasAsociadasCB = new JComboBox<>();
        jLabel1 = new JLabel();
        jScrollPane1 = new JScrollPane();
        ListaAprendicesFichaTable = new JTable();

        jPanel1.setBackground(new Color(255, 255, 255));

        FichasAsociadasCB.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        FichasAsociadasCB.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                FichasAsociadasCBActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new Color(0, 0, 0));
        jLabel1.setText("Fichas Asociadas");

        ListaAprendicesFichaTable.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ListaAprendicesFichaTable);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(FichasAsociadasCB, GroupLayout.PREFERRED_SIZE, 236, GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FichasAsociadasCB, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FichasAsociadasCBActionPerformed(ActionEvent evt) {//GEN-FIRST:event_FichasAsociadasCBActionPerformed
        API_Admin_AprendizApplications api = new API_Admin_AprendizApplications();
        List<AprendizModel> aprendices = null;

        // Verificar si se seleccionó una ficha válida
        String selectedFicha = FichasAsociadasCB.getSelectedItem().toString();
        if (!selectedFicha.equals("Seleccionar...")) {
            try {
                // Convertir el valor seleccionado a Integer
                Integer numeroFicha = Integer.parseInt(selectedFicha);
                aprendices = api.obtenerAprendicesCompletosPorFicha(numeroFicha);

                // Limpiar la tabla antes de añadir nuevos datos
                ListarApModel.setRowCount(0);

                // Iterar sobre la lista de aprendices y agregar cada uno a la tabla
                for (AprendizModel aprendiz : aprendices) {
                    System.out.println("Aprendiz: " + aprendiz);

                    ListarApModel.addRow(new Object[]{
                            aprendiz.getDocumento(),
                            aprendiz.getTipoDocumento(),
                            aprendiz.getNombres() + " " + aprendiz.getApellidos(),
                            aprendiz.getFechaNacimiento().toString(),
                            aprendiz.getTelefono(),
                            aprendiz.getCorreo(),
                            aprendiz.getGenero(),
                            aprendiz.getResidencia(),
                            aprendiz.getFicha(),
                            aprendiz.getProgramaFormacion(),
                            aprendiz.getJornadaFormacion(),
                            aprendiz.getNivelFormacion(),
                            aprendiz.getSede(),
                            aprendiz.getArea()
                    });
                }

                // Asegurarse de que la tabla esté usando el modelo actualizado
                ListaAprendicesFichaTable.setModel(ListarApModel);
                ListaAprendicesFichaTable.revalidate();
                ListaAprendicesFichaTable.repaint();

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error al convertir el valor de la ficha: " + e.getMessage());
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }

    }//GEN-LAST:event_FichasAsociadasCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JComboBox<String> FichasAsociadasCB;
    private JTable ListaAprendicesFichaTable;
    private JLabel jLabel1;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
