/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.AdminFrames.AdminActionScreens.ModUserSubPanel;


import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Map;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.ArrayList;
import main.util.API_Actions.API_BuscarUsuario;

import main.util.API_AdminActions.API_Admin_UsersApplications.API_Admin_InstructorApplications;
import main.util.models.*;
import main.util.models.UsersModels.InstructorModel;

/**
 *
 * @author usuario
 */
public class ModInstructorSubPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateInstructorSubPanel
     */
    DefaultComboBoxModel<String> yearModel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> mesModel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> diaModel = new DefaultComboBoxModel<>();
    DefaultTableModel modeloTabla = new DefaultTableModel(
            new Object[] {"Ficha", "Programa de Formación", "Nivel de Formación", "Jornada de Formación", "Sede", "Área", "Eliminar"},
            0  // Número de filas iniciales
    );

    public ModInstructorSubPanel() {
        initComponents();
        aditionalConfig();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateInstructorSubPanel = new javax.swing.JPanel();
        ConfirmarRegistroUsuario = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ResidenciaHolder = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        ResultadoFechaHolder = new javax.swing.JTextField();
        DiaCB = new javax.swing.JComboBox<>();
        MesCB = new javax.swing.JComboBox<>();
        ResultadoArea = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        ResultadoNombres = new javax.swing.JTextField();
        ResultadoSede = new javax.swing.JTextField();
        ResultadoPass = new javax.swing.JTextField();
        ResultadoNivelFormacion = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        GeneroCB = new javax.swing.JComboBox<>();
        ResultadoUsuario = new javax.swing.JTextField();
        TipoDocCB = new javax.swing.JComboBox<>();
        ResultadoDocumento = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        ResultadoApellidos = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        MunicipioCB = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        BarrioCB = new javax.swing.JComboBox<>();
        ResultadoCorreo = new javax.swing.JTextField();
        DepartamentoCB = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        ResultadoJornadaFormacion = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        YearCB = new javax.swing.JComboBox<>();
        ResultadoTelefono = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        FichaCB = new javax.swing.JComboBox<>();
        ResultadoProgramaFormacion = new javax.swing.JTextField();
        AsociarFicha = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FichasAsociadasTB = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        IDInstructorField = new javax.swing.JTextField();
        BuscarDatosUsuario = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        ClaseFormacionCB = new javax.swing.JComboBox<>();

        CreateInstructorSubPanel.setBackground(new java.awt.Color(255, 255, 255));

        ConfirmarRegistroUsuario.setBackground(new java.awt.Color(0, 34, 64));
        ConfirmarRegistroUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmarRegistroUsuario.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmarRegistroUsuario.setText("Modificar Instructor");
        ConfirmarRegistroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarRegistroUsuarioActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Usuario");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Sede");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Genero");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Tipo de documento");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Apellidos");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Nombres");

        ResidenciaHolder.setEditable(false);
        ResidenciaHolder.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResidenciaHolder.setForeground(new java.awt.Color(0, 0, 0));
        ResidenciaHolder.setFocusable(false);

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Nivel de formacion");

        ResultadoFechaHolder.setEditable(false);
        ResultadoFechaHolder.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResultadoFechaHolder.setForeground(new java.awt.Color(0, 0, 0));
        ResultadoFechaHolder.setFocusable(false);

        DiaCB.setForeground(new java.awt.Color(0, 0, 0));
        DiaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DiaCB.setEnabled(false);
        DiaCB.setPreferredSize(new java.awt.Dimension(64, 28));
        DiaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaCBActionPerformed(evt);
            }
        });

        MesCB.setForeground(new java.awt.Color(0, 0, 0));
        MesCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MesCB.setEnabled(false);
        MesCB.setPreferredSize(new java.awt.Dimension(64, 28));
        MesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesCBActionPerformed(evt);
            }
        });

        ResultadoArea.setEditable(false);
        ResultadoArea.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResultadoArea.setForeground(new java.awt.Color(0, 0, 0));
        ResultadoArea.setFocusable(false);
        ResultadoArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoAreaActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Correo");

        ResultadoNombres.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResultadoNombres.setForeground(new java.awt.Color(0, 0, 0));
        ResultadoNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ResultadoNombresKeyTyped(evt);
            }
        });

        ResultadoSede.setEditable(false);
        ResultadoSede.setFocusable(false);

        ResultadoPass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResultadoPass.setForeground(new java.awt.Color(0, 0, 0));
        ResultadoPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoPassActionPerformed(evt);
            }
        });

        ResultadoNivelFormacion.setEditable(false);
        ResultadoNivelFormacion.setFocusable(false);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Contraseña");

        GeneroCB.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        GeneroCB.setForeground(new java.awt.Color(0, 0, 0));
        GeneroCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        GeneroCB.setPreferredSize(new java.awt.Dimension(64, 28));
        GeneroCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroCBActionPerformed(evt);
            }
        });

        ResultadoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResultadoUsuario.setForeground(new java.awt.Color(0, 0, 0));

        TipoDocCB.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TipoDocCB.setForeground(new java.awt.Color(0, 0, 0));
        TipoDocCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TipoDocCB.setPreferredSize(new java.awt.Dimension(64, 28));
        TipoDocCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDocCBActionPerformed(evt);
            }
        });

        ResultadoDocumento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResultadoDocumento.setForeground(new java.awt.Color(0, 0, 0));
        ResultadoDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ResultadoDocumentoKeyTyped(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Programa de Formacion");

        ResultadoApellidos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResultadoApellidos.setForeground(new java.awt.Color(0, 0, 0));
        ResultadoApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ResultadoApellidosKeyTyped(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Numero de ficha");

        MunicipioCB.setForeground(new java.awt.Color(0, 0, 0));
        MunicipioCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MunicipioCB.setEnabled(false);
        MunicipioCB.setPreferredSize(new java.awt.Dimension(64, 28));
        MunicipioCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MunicipioCBActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Documento");

        BarrioCB.setForeground(new java.awt.Color(0, 0, 0));
        BarrioCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BarrioCB.setEnabled(false);
        BarrioCB.setPreferredSize(new java.awt.Dimension(64, 28));
        BarrioCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarrioCBActionPerformed(evt);
            }
        });

        ResultadoCorreo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResultadoCorreo.setForeground(new java.awt.Color(0, 0, 0));

        DepartamentoCB.setForeground(new java.awt.Color(0, 0, 0));
        DepartamentoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DepartamentoCB.setPreferredSize(new java.awt.Dimension(64, 28));
        DepartamentoCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartamentoCBActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Residencia");

        ResultadoJornadaFormacion.setEditable(false);
        ResultadoJornadaFormacion.setFocusable(false);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Area de trabajo");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Telefono");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Jornada de formacion");

        YearCB.setForeground(new java.awt.Color(0, 0, 0));
        YearCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        YearCB.setPreferredSize(new java.awt.Dimension(64, 28));
        YearCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearCBActionPerformed(evt);
            }
        });

        ResultadoTelefono.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResultadoTelefono.setForeground(new java.awt.Color(0, 0, 0));
        ResultadoTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ResultadoTelefonoKeyTyped(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Fecha de Nacimiento");

        FichaCB.setForeground(new java.awt.Color(0, 0, 0));
        FichaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        FichaCB.setPreferredSize(new java.awt.Dimension(64, 28));
        FichaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FichaCBActionPerformed(evt);
            }
        });

        ResultadoProgramaFormacion.setEditable(false);
        ResultadoProgramaFormacion.setFocusable(false);

        AsociarFicha.setBackground(new java.awt.Color(57, 169, 0));
        AsociarFicha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        AsociarFicha.setForeground(new java.awt.Color(255, 255, 255));
        AsociarFicha.setText("AsociarFicha");
        AsociarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsociarFichaActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fichas Asociadas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        FichasAsociadasTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        FichasAsociadasTB.setFocusable(false);
        FichasAsociadasTB.setRequestFocusEnabled(false);
        FichasAsociadasTB.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(FichasAsociadasTB);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Documento del usuario");

        IDInstructorField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        IDInstructorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDInstructorFieldActionPerformed(evt);
            }
        });
        IDInstructorField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDInstructorFieldKeyTyped(evt);
            }
        });

        BuscarDatosUsuario.setBackground(new java.awt.Color(57, 169, 0));
        BuscarDatosUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BuscarDatosUsuario.setForeground(new java.awt.Color(255, 255, 255));
        BuscarDatosUsuario.setText("Buscar");
        BuscarDatosUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarDatosUsuarioActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Clase de formacion");

        ClaseFormacionCB.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ClaseFormacionCB.setForeground(new java.awt.Color(0, 0, 0));
        ClaseFormacionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ClaseFormacionCB.setPreferredSize(new java.awt.Dimension(64, 28));
        ClaseFormacionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClaseFormacionCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreateInstructorSubPanelLayout = new javax.swing.GroupLayout(CreateInstructorSubPanel);
        CreateInstructorSubPanel.setLayout(CreateInstructorSubPanelLayout);
        CreateInstructorSubPanelLayout.setHorizontalGroup(
            CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConfirmarRegistroUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(85, 85, 85)
                        .addComponent(FichaCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AsociarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                        .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel17))
                                .addGap(95, 95, 95)
                                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ResultadoArea)
                                    .addComponent(ResultadoSede)))
                            .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel41))
                                .addGap(33, 33, 33)
                                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ResultadoNivelFormacion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ResultadoProgramaFormacion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ResultadoJornadaFormacion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                        .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 1032, Short.MAX_VALUE))
                            .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28))
                                .addGap(67, 67, 67)
                                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TipoDocCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ResultadoNombres, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ResultadoApellidos, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ResultadoPass)
                                    .addComponent(ResultadoUsuario)))
                            .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(120, 120, 120)
                                .addComponent(ResultadoDocumento))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateInstructorSubPanelLayout.createSequentialGroup()
                                .addComponent(IDInstructorField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BuscarDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel25))
                                .addGap(56, 56, 56)
                                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                                        .addComponent(YearCB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MesCB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DiaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ResultadoFechaHolder, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                                    .addComponent(GeneroCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ResultadoTelefono)
                                    .addComponent(ResultadoCorreo)
                                    .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                                        .addComponent(DepartamentoCB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MunicipioCB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BarrioCB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ResidenciaHolder))
                                    .addComponent(ClaseFormacionCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        CreateInstructorSubPanelLayout.setVerticalGroup(
            CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDInstructorField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResultadoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(9, 9, 9)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19))
                    .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                        .addComponent(ResultadoPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ResultadoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoDocCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResultadoNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResultadoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel25)
                        .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(YearCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MesCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DiaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ResultadoFechaHolder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GeneroCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResultadoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(ResultadoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DepartamentoCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MunicipioCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BarrioCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ResidenciaHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClaseFormacionCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(FichaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AsociarFicha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                        .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addComponent(ResultadoProgramaFormacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(ResultadoNivelFormacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(ResultadoJornadaFormacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(ResultadoArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(ResultadoSede, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmarRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateInstructorSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateInstructorSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
        public void aditionalConfig(){
            try {
                ButtonStyler buttonStyler = new ButtonStyler();
                buttonStyler.applyPrimaryStyle(AsociarFicha);
                yearModel.addElement("Seleccionar Año");
                llenarYear(yearModel);
                mesModel.addElement("Seleccionar Mes");
                diaModel.addElement("Seleccionar Día");
                FichasAsociadasTB.setModel(modeloTabla);
                ComboBoxModels CBModels = new ComboBoxModels();
                TipoDocCB.setModel(CBModels.generarComboBoxModelPorTipo("TipoDocumento"));
                GeneroCB.setModel(CBModels.generarComboBoxModelPorTipo("Genero"));
                MunicipioCB.setModel(CBModels.generarComboBoxModelPorTipo("Municipios"));
                DepartamentoCB.setModel(CBModels.generarComboBoxModelPorTipo("Departamentos"));
                BarrioCB.setModel(CBModels.generarComboBoxModelPorTipo("Barrios"));
                FichaCB.setModel(CBModels.generarComboBoxModelPorTipo("Fichas"));
                YearCB.setModel(yearModel);
                MesCB.setModel(mesModel);
                DiaCB.setModel(diaModel);
                ClaseFormacionCB.setModel(CBModels.generarComboBoxModelPorTipo("ClaseFormacion"));
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
        
         private void llenarYear(DefaultComboBoxModel<String> anhoModel) {
        int anhoActual = Calendar.getInstance().get(Calendar.YEAR);
        for (int i = anhoActual; i > anhoActual - 100; i--) {
            anhoModel.addElement(String.valueOf(i));
        }
    }

    public void llenarMeses() {
        mesModel.removeAllElements();
        mesModel.addElement("Seleccionar Mes");
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
                "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        for (String mes : meses) {
            mesModel.addElement(mes);
        }
    }

    private void llenarDias(DefaultComboBoxModel<String> diaModel, int anho, int mes) {
        diaModel.removeAllElements();
        diaModel.addElement("Seleccionar Día");
        int diasEnMes = obtenerDiasDelMes(anho, mes);
        for (int i = 1; i <= diasEnMes; i++) {
            diaModel.addElement(String.valueOf(i));
        }
    }

    private int obtenerDiasDelMes(int anho, int mes) {
        switch (mes) {
            case 1: case 3: case 5: case 7: case 8: case 10: case 12:
                return 31;
            case 4: case 6: case 9: case 11:
                return 30;
            case 2:
                return (anho % 4 == 0 && (anho % 100 != 0 || anho % 400 == 0)) ? 29 : 28;
            default:
                return 30;
        }
    }

    private int obtenerNumeroMes(String mesSeleccionado) {
        switch (mesSeleccionado) {
            case "Enero": return 1;
            case "Febrero": return 2;
            case "Marzo": return 3;
            case "Abril": return 4;
            case "Mayo": return 5;
            case "Junio": return 6;
            case "Julio": return 7;
            case "Agosto": return 8;
            case "Septiembre": return 9;
            case "Octubre": return 10;
            case "Noviembre": return 11;
            case "Diciembre": return 12;
            default: return -1; // En caso de error
        }
    }

    private void actualizarFecha() {
        String anhoSeleccionado = (String) YearCB.getSelectedItem();
        String mesSeleccionado = (String) MesCB.getSelectedItem();
        String diaSeleccionado = (String) DiaCB.getSelectedItem();

        // Comprobar si los tres elementos han sido seleccionados correctamente
        if (anhoSeleccionado != null && !anhoSeleccionado.equals("Seleccionar Año") &&
                mesSeleccionado != null && !mesSeleccionado.equals("Seleccionar Mes") &&
                diaSeleccionado != null && !diaSeleccionado.equals("Seleccionar Día")) {

            // Convertir el nombre del mes a su número usando obtenerNumeroMes()
            int numeroMes = obtenerNumeroMes(mesSeleccionado);
            String mesConFormato = (numeroMes < 10 ? "0" : "") + numeroMes; // Formatear el mes con cero si es necesario
            String diaConFormato = (Integer.parseInt(diaSeleccionado) < 10 ? "0" : "") + diaSeleccionado; // Formatear el día con cero si es necesario

            // Mostrar la fecha en formato "yyyy-MM-dd"
            ResultadoFechaHolder.setText(anhoSeleccionado + "-" + mesConFormato + "-" + diaConFormato);
        } else {
            // Si alguno no está seleccionado, mostrar el campo vacío o parcialmente seleccionado
            String fechaParcial = "";
            if (anhoSeleccionado != null && !anhoSeleccionado.equals("Seleccionar Año")) {
                fechaParcial += anhoSeleccionado;
            }
            if (mesSeleccionado != null && !mesSeleccionado.equals("Seleccionar Mes")) {
                int numeroMes = obtenerNumeroMes(mesSeleccionado);
                String mesConFormato = (numeroMes < 10 ? "0" : "") + numeroMes; // Formatear el mes con cero si es necesario
                if (!fechaParcial.isEmpty()) {
                    fechaParcial += "-";  // Solo añadir el guion si ya hay algo en la fecha parcial
                }
                fechaParcial += mesConFormato;
            }
            if (diaSeleccionado != null && !diaSeleccionado.equals("Seleccionar Día")) {
                String diaConFormato = (Integer.parseInt(diaSeleccionado) < 10 ? "0" : "") + diaSeleccionado; // Formatear el día con cero si es necesario
                if (!fechaParcial.isEmpty()) {
                    fechaParcial += "-";  // Solo añadir el guion si ya hay algo en la fecha parcial
                }
                fechaParcial += diaConFormato;
            }
            ResultadoFechaHolder.setText(fechaParcial); // Mostrar la selección parcial
        }
    }
    
    private void actualizarResidencia() {
        String departamentoSeleccionado = (String) DepartamentoCB.getSelectedItem();
        String municipioSeleccionado = (String) MunicipioCB.getSelectedItem();
        String barrioSeleccionado = (String) BarrioCB.getSelectedItem();

        // Comprobar si los tres elementos han sido seleccionados correctamente
        if (departamentoSeleccionado != null && !departamentoSeleccionado.equals("Seleccionar...") &&
            municipioSeleccionado != null && !municipioSeleccionado.equals("Seleccionar...") &&
            barrioSeleccionado != null && !barrioSeleccionado.equals("Seleccionar...")) {

            // Mostrar la residencia en formato "Departamento - Municipio - Barrio"
            ResidenciaHolder.setText(departamentoSeleccionado + " - " + municipioSeleccionado + " - " + barrioSeleccionado);
        } else {
            // Si alguno no está seleccionado, mostrar el campo parcial
            String residenciaParcial = "";
            if (departamentoSeleccionado != null && !departamentoSeleccionado.equals("Seleccionar...")) {
                residenciaParcial += departamentoSeleccionado;
            }
            if (municipioSeleccionado != null && !municipioSeleccionado.equals("Seleccionar...")) {
                if (!residenciaParcial.isEmpty()) {
                    residenciaParcial += " - ";  // Solo añadir el separador si hay un valor previo
                }
                residenciaParcial += municipioSeleccionado;
            }
            if (barrioSeleccionado != null && !barrioSeleccionado.equals("Seleccionar...")) {
                if (!residenciaParcial.isEmpty()) {
                    residenciaParcial += " - ";  // Solo añadir el separador si hay un valor previo
                }
                residenciaParcial += barrioSeleccionado;
            }
            ResidenciaHolder.setText(residenciaParcial);  // Mostrar la selección parcial
        }
    }

    private void ConfirmarRegistroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarRegistroUsuarioActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea registrar los datos?", "Confirmación", JOptionPane.YES_NO_CANCEL_OPTION);

        switch (respuesta) {
            case JOptionPane.YES_OPTION -> {
                try {
                    SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                    java.util.Date fechaNacimientoUtil = null;
                    java.sql.Date fechaNacimiento = null;

                    try {
                        // Intentar convertir la fecha del holder a un objeto java.util.Date en formato "yyyy-MM-dd"
                        String fechaTexto = ResultadoFechaHolder.getText();
                        System.out.println("Fecha ingresada: " + fechaTexto);

                        fechaNacimientoUtil = formatoFecha.parse(fechaTexto);

                        // Convertir java.util.Date a java.sql.Date
                        fechaNacimiento = new java.sql.Date(fechaNacimientoUtil.getTime());
                        System.out.println("Fecha convertida a java.sql.Date: " + fechaNacimiento);

                    } catch (ParseException e) {
                        e.printStackTrace();  // Manejar la excepción si la fecha no está en el formato correcto
                        try {
                            // Asignar una fecha predeterminada en caso de error y convertirla a java.sql.Date
                            System.out.println("Formato incorrecto. Usando fecha por defecto '1990-05-10'.");
                            fechaNacimientoUtil = formatoFecha.parse("1990-05-10");
                            fechaNacimiento = new java.sql.Date(fechaNacimientoUtil.getTime());
                        } catch (ParseException ex) {
                            throw new RuntimeException(ex);
                        }
                    }

                    // Capturar los datos de la tabla FichasAsociadasTB
                    DefaultTableModel modeloTabla = (DefaultTableModel) FichasAsociadasTB.getModel();
                    int filas = modeloTabla.getRowCount();

                    List<Integer> fichas = new ArrayList<>();
                    List<String> programasFormacion = new ArrayList<>();
                    List<String> jornadasFormacion = new ArrayList<>();
                    List<String> nivelesFormacion = new ArrayList<>();
                    List<String> sedes = new ArrayList<>();
                    List<String> areas = new ArrayList<>();

                    for (int i = 0; i < filas; i++) {
                        fichas.add((Integer) modeloTabla.getValueAt(i, 0));  // Ficha en la columna 0
                        programasFormacion.add((String) modeloTabla.getValueAt(i, 1));  // Programa de formación en la columna 1
                        nivelesFormacion.add((String) modeloTabla.getValueAt(i, 2));  // Nivel de formación en la columna 2
                        jornadasFormacion.add((String) modeloTabla.getValueAt(i, 3));  // Jornada de formación en la columna 3
                        sedes.add((String) modeloTabla.getValueAt(i, 4));  // Sede en la columna 4
                        areas.add((String) modeloTabla.getValueAt(i, 5));  // Área en la columna 5
                    }

                    // Crear el objeto InstructorModel
                    InstructorModel instructor = new InstructorModel(
                            ResultadoUsuario.getText(),
                            ResultadoPass.getText(),
                            ResultadoDocumento.getText(),
                            TipoDocCB.getSelectedItem().toString(),
                            ResultadoNombres.getText(),
                            ResultadoApellidos.getText(),
                            fechaNacimiento,  // Asegúrate de convertir la fecha correctamente
                            ResultadoTelefono.getText(),
                            ResultadoCorreo.getText(),
                            GeneroCB.getSelectedItem().toString(),
                            ResidenciaHolder.getText(),
                            ClaseFormacionCB.getSelectedItem().toString(),
                            fichas,
                            programasFormacion,
                            jornadasFormacion,
                            nivelesFormacion,
                            sedes,
                            areas
                    );

                    // Enviar el modelo a la API
                    API_Admin_InstructorApplications actualizarInstructor = new API_Admin_InstructorApplications();
                    actualizarInstructor.UpdateInstructor(ResultadoDocumento.getText(), instructor);

                    // Limpiar formulario después de la actualización
                    limpiarFormularioInstructor();

                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error al enviar los datos del instructor: " + e.getMessage());
                }
            }

            case JOptionPane.NO_OPTION, JOptionPane.CANCEL_OPTION -> {
                // Acción para NO o CANCELAR
            }
        }
    }//GEN-LAST:event_ConfirmarRegistroUsuarioActionPerformed


    private void limpiarFormularioInstructor() {
        ResultadoUsuario.setText("");
        ResultadoPass.setText("");
        ResultadoDocumento.setText("");
        ResultadoNombres.setText("");
        ResultadoApellidos.setText("");
        ResultadoTelefono.setText("");
        ResultadoCorreo.setText("");
        ResidenciaHolder.setText("");
        ResultadoFechaHolder.setText("");
        ResultadoProgramaFormacion.setText("");
        ResultadoNivelFormacion.setText("");
        ResultadoJornadaFormacion.setText("");
        ResultadoArea.setText("");
        ResultadoSede.setText("");

        // Restablecer JComboBoxes
        TipoDocCB.setSelectedIndex(0);  // Asumiendo que el índice 0 es "Seleccionar..."
        YearCB.setSelectedIndex(0);
        MesCB.setSelectedIndex(0);
        MesCB.setEnabled(false);
        DiaCB.setSelectedIndex(0);
        DiaCB.setEnabled(false);
        GeneroCB.setSelectedIndex(0);  // Asumiendo que el índice 0 es "Seleccionar..."
        DepartamentoCB.setSelectedIndex(0);
        MunicipioCB.setSelectedIndex(0);
        MunicipioCB.setEnabled(false);
        BarrioCB.setSelectedIndex(0);
        BarrioCB.setEnabled(false);
        FichaCB.setSelectedIndex(0);

        modeloTabla.setRowCount(0);  // Vaciar todas las filas de la tabla

        // Otros campos de tipo JComboBox o componentes pueden ser reseteados aquí
    }

    private void DiaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaCBActionPerformed
        String diaSeleccionado = (String) DiaCB.getSelectedItem();

        if (diaSeleccionado != null && !diaSeleccionado.equals("Seleccionar Día")) {
            actualizarFecha();  // Llamada al método para actualizar el TextField
        }
    }//GEN-LAST:event_DiaCBActionPerformed

    private void MesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesCBActionPerformed
        String mesSeleccionado = (String) MesCB.getSelectedItem();

        // Verificamos si es "Seleccionar Mes"
        if (mesSeleccionado == null || mesSeleccionado.equals("Seleccionar Mes")) {
            diaModel.removeAllElements();   // Limpiar los días
            diaModel.addElement("Seleccionar Día");  // Volver a poner la opción por defecto
            DiaCB.setEnabled(false);  // Deshabilitar el ComboBox de Día
        } else {
            // Si se selecciona un mes válido, llenar los días
            int anho = Integer.parseInt((String) YearCB.getSelectedItem());
            int numeroMes = obtenerNumeroMes(mesSeleccionado);  // Obtener el número correcto del mes

            // Llenar los días en el ComboBox de Día
            llenarDias(diaModel, anho, numeroMes);
            DiaCB.setEnabled(true);  // Habilitar el ComboBox de Día
        }

        actualizarFecha();  // Actualizar el TextField FechaHolder
    }//GEN-LAST:event_MesCBActionPerformed

    private void ResultadoPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoPassActionPerformed

    private void GeneroCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroCBActionPerformed

    private void TipoDocCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDocCBActionPerformed

    }//GEN-LAST:event_TipoDocCBActionPerformed

    private void MunicipioCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MunicipioCBActionPerformed
        String municipioSeleccionado = (String) MunicipioCB.getSelectedItem();

        if (municipioSeleccionado != null && !municipioSeleccionado.equals("Seleccionar...")) {
            BarrioCB.setEnabled(true);  // Habilitar el ComboBox de Barrio
        } else {
            BarrioCB.setEnabled(false);  // Deshabilitar el ComboBox de Barrio si no se selecciona un municipio válido
            BarrioCB.setSelectedItem("Seleccionar...");   // Situar el Barrio en "Seleccionar..."
        }

        actualizarResidencia();  // Actualizar el ResidenciaHolder
    }//GEN-LAST:event_MunicipioCBActionPerformed

    private void BarrioCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarrioCBActionPerformed
        actualizarResidencia();  // Llamar al método para actualizar el ResidenciaHolder
    }//GEN-LAST:event_BarrioCBActionPerformed

    private void DepartamentoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartamentoCBActionPerformed
        String departamentoSeleccionado = (String) DepartamentoCB.getSelectedItem();

        if (departamentoSeleccionado != null && !departamentoSeleccionado.equals("Seleccionar...")) {
            MunicipioCB.setEnabled(true);  // Habilitar el ComboBox de Municipio
            BarrioCB.setEnabled(false);    // Deshabilitar el ComboBox de Barrio hasta que se seleccione un municipio
            BarrioCB.setSelectedItem("Seleccionar...");  // Situar el Barrio en "Seleccionar..."
        } else {
            // Si no se ha seleccionado un departamento válido, deshabilitar Municipio y Barrio
            MunicipioCB.setEnabled(false);
            BarrioCB.setEnabled(false);
            MunicipioCB.setSelectedItem("Seleccionar...");  // Situar el Municipio en "Seleccionar..."
            BarrioCB.setSelectedItem("Seleccionar...");     // Situar el Barrio en "Seleccionar..."
        }

        actualizarResidencia();  // Actualizar el ResidenciaHolder
    }//GEN-LAST:event_DepartamentoCBActionPerformed

    private void YearCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearCBActionPerformed
        String YearSeleccionado = (String) YearCB.getSelectedItem();

        // Verificamos si es "Seleccionar Año"
        if (YearSeleccionado == null || YearSeleccionado.equals("Seleccionar Año")) {
            mesModel.removeAllElements();   // Limpiar los meses
            mesModel.addElement("Seleccionar Mes");  // Volver a poner la opción por defecto
            MesCB.setEnabled(false);  // Deshabilitar el ComboBox de Mes

            diaModel.removeAllElements();   // Limpiar los días
            diaModel.addElement("Seleccionar Día");  // Volver a poner la opción por defecto
            DiaCB.setEnabled(false);  // Deshabilitar el ComboBox de Día
        } else {
            // Si se selecciona un año válido, llenar los meses
            llenarMeses();  // Llenar los meses
            MesCB.setEnabled(true);  // Habilitar el ComboBox de Mes
            DiaCB.setEnabled(false); // Deshabilitar el ComboBox de Día hasta que se seleccione un mes
            DiaCB.removeAllItems();  // Limpiar los días por si acaso
        }

        actualizarFecha();  // Actualizar el TextField FechaHolder
    }//GEN-LAST:event_YearCBActionPerformed

    private void FichaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FichaCBActionPerformed
        String fichaSeleccionada = (String) FichaCB.getSelectedItem();

        if (fichaSeleccionada != null && !fichaSeleccionada.equals("Seleccionar...")) {
            try {
                // Convertir el valor seleccionado a un número de ficha (si corresponde)
                int ficha = Integer.parseInt(fichaSeleccionada);
                System.out.println(ficha);

                // Crear una instancia de DataTables para realizar la consulta
                DataTables dataTables = new DataTables();

                // Consultar el programa de formación por la ficha seleccionada
                Map<String, Object> FichaDataResult = dataTables.obtenerProgramaFormacionPorFicha(ficha);
                System.out.println(FichaDataResult);

                if (FichaDataResult != null) {
                    // Colocar el valor obtenido en el JTextField correspondiente
                    ResultadoProgramaFormacion.setText((String) FichaDataResult.get("ProgramaFormacion"));
                    ResultadoNivelFormacion.setText((String) FichaDataResult.get("NivelFormacion"));
                    ResultadoJornadaFormacion.setText((String) FichaDataResult.get("JornadasFormacion"));
                    ResultadoSede.setText((String) FichaDataResult.get("Sede"));
                    ResultadoArea.setText((String) FichaDataResult.get("Area"));

                } else {
                    // Si no se obtiene un resultado válido, limpiar el campo de texto
                    ResultadoProgramaFormacion.setText((String) FichaDataResult.get("ProgramaFormacion No encontrado"));
                    ResultadoNivelFormacion.setText((String) FichaDataResult.get("NivelFormacion No encontrado"));
                    ResultadoJornadaFormacion.setText((String) FichaDataResult.get("JornadasFormacion No encontrado"));
                    ResultadoSede.setText((String) FichaDataResult.get("Sede No encontrado"));
                    ResultadoArea.setText((String) FichaDataResult.get("Area No encontrado"));
                }
            } catch (NumberFormatException ex) {
                ex.printStackTrace();
                ResultadoProgramaFormacion.setText("ProgramaFormacion Invalida");
                ResultadoNivelFormacion.setText("NivelFormacion Invalida");
                ResultadoJornadaFormacion.setText("JornadasFormacion Invalida");
                ResultadoSede.setText("Sede Invalida");
                ResultadoArea.setText("Area Invalida");
            }
        } else {
            // Limpiar el campo si no hay selección válida
            ResultadoProgramaFormacion.setText("");
            ResultadoNivelFormacion.setText("");
            ResultadoJornadaFormacion.setText("");
            ResultadoSede.setText("");
            ResultadoArea.setText("");
        }
    }//GEN-LAST:event_FichaCBActionPerformed

    private void AsociarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsociarFichaActionPerformed
        String fichaSeleccionada = (String) FichaCB.getSelectedItem();

        // Verificar si se ha seleccionado una ficha válida
        if (fichaSeleccionada != null && !fichaSeleccionada.equals("Seleccionar...")) {
            try {
                // Convertir el valor seleccionado a un número de ficha (si corresponde)
                int ficha = Integer.parseInt(fichaSeleccionada);

                // Verificar si la ficha ya está asociada en la tabla
                if (fichaYaAsociada(ficha)) {
                    JOptionPane.showMessageDialog(null, "La ficha " + ficha + " ya está asociada.", "Error", JOptionPane.ERROR_MESSAGE);
                    return; // Salir del método si la ficha ya está asociada
                }

                // Crear una instancia de DataTables para realizar la consulta
                DataTables dataTables = new DataTables();

                // Consultar el programa de formación por la ficha seleccionada
                Map<String, Object> FichaDataResult = dataTables.obtenerProgramaFormacionPorFicha(ficha);

                // Si se obtuvieron resultados válidos, agregar la ficha a la tabla
                if (FichaDataResult != null) {
                    // Obtener los valores del resultado de la consulta
                    String programaFormacion = (String) FichaDataResult.get("ProgramaFormacion");
                    String nivelFormacion = (String) FichaDataResult.get("NivelFormacion");
                    String jornadaFormacion = (String) FichaDataResult.get("JornadasFormacion");
                    String sede = (String) FichaDataResult.get("Sede");
                    String area = (String) FichaDataResult.get("Area");

                    // Obtener el modelo de la tabla
                    DefaultTableModel modeloTabla = (DefaultTableModel) FichasAsociadasTB.getModel();

                    // Agregar una nueva fila con los valores obtenidos
                    modeloTabla.addRow(new Object[] {ficha, programaFormacion, nivelFormacion, jornadaFormacion, sede, area, "Eliminar"});

                    // Configurar los renderers y editores para la columna "Eliminar"
                    FichasAsociadasTB.getColumn("Eliminar").setCellRenderer(new ButtonColumnHelper.ButtonRenderer());
                    FichasAsociadasTB.getColumn("Eliminar").setCellEditor(new ButtonColumnHelper.ButtonEditor(new JCheckBox(), FichasAsociadasTB));

                    // Imprimir el contenido de la tabla después de agregar la fila
                    imprimirContenidoTabla();

                } else {
                    // Si no se obtuvieron resultados válidos, mostrar un mensaje de error
                    JOptionPane.showMessageDialog(null, "Ficha no encontrada o datos incompletos", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (NumberFormatException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Ficha inválida", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Si no se ha seleccionado una ficha válida, mostrar un mensaje de advertencia
            JOptionPane.showMessageDialog(null, "Debe seleccionar una ficha válida", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_AsociarFichaActionPerformed

    private void ResultadoAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoAreaActionPerformed

    private void IDInstructorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDInstructorFieldActionPerformed
        BuscarDatosUsuario.doClick();
    }//GEN-LAST:event_IDInstructorFieldActionPerformed

    private void BuscarDatosUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarDatosUsuarioActionPerformed
        // Crea una nueva instancia de API_BuscarUsuario para buscar un instructor
        API_BuscarUsuario buscarInstructor = new API_BuscarUsuario();

        // Intenta buscar el instructor en la base de datos usando el documento ingresado
        InstructorModel instructor = buscarInstructor.buscarInstructorPorDocumento(IDInstructorField.getText());

        if (instructor != null) {
            // Rellenar los campos con los datos del instructor

            // Nombre de usuario
            ResultadoUsuario.setText(instructor.getUser());

            // Documento y tipo de documento
            ResultadoDocumento.setText(instructor.getDocumento());
            TipoDocCB.setSelectedItem(instructor.getTipoDocumento());

            // Nombres y apellidos
            ResultadoNombres.setText(instructor.getNombres());
            ResultadoApellidos.setText(instructor.getApellidos());

            // Fecha de nacimiento (convertir java.sql.Date a String en formato "yyyy-MM-dd")
            Date fechaNacimiento = instructor.getFechaNacimiento();
            if (fechaNacimiento != null) {
                LocalDate fecha = fechaNacimiento.toLocalDate();
                int anho = fecha.getYear();
                int mes = fecha.getMonthValue();
                int dia = fecha.getDayOfMonth();

                // Setear YearCB, MesCB, DiaCB
                YearCB.setSelectedItem(String.valueOf(anho));

                String[] mesesNombres = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
                String nombreMes = mesesNombres[mes - 1];
                MesCB.setSelectedItem(nombreMes);

                // Setear DiaCB
                DiaCB.setSelectedItem(String.valueOf(dia));
            }

            // Género
            GeneroCB.setSelectedItem(instructor.getGenero());

            // Correo y teléfono
            ResultadoCorreo.setText(instructor.getCorreo());
            ResultadoTelefono.setText(instructor.getTelefono());

            // Residencia
            String[] residencia = instructor.getResidencia().split(" - ");
            if (residencia.length == 3) {
                DepartamentoCB.setSelectedItem(residencia[0]);
                MunicipioCB.setSelectedItem(residencia[1]);
                BarrioCB.setSelectedItem(residencia[2]);
            }

            // Limpiar los campos relacionados con las fichas
            ResultadoProgramaFormacion.setText("");
            ResultadoNivelFormacion.setText("");
            ResultadoJornadaFormacion.setText("");
            ResultadoSede.setText("");
            ResultadoArea.setText("");

            // Fichas y programas de formación
            DefaultTableModel modeloTabla = (DefaultTableModel) FichasAsociadasTB.getModel();
            modeloTabla.setRowCount(0);  // Limpiar la tabla

            // Recorrer las listas de fichas, programas, jornadas, niveles, sedes y áreas para agregarlos a la tabla
            List<Integer> fichas = instructor.getFichas();
            List<String> programasFormacion = instructor.getProgramasFormacion();
            List<String> jornadasFormacion = instructor.getJornadasFormacion();
            List<String> nivelesFormacion = instructor.getNivelesFormacion();
            List<String> sedes = instructor.getSedes();
            List<String> areas = instructor.getAreas();

            // Verificar el tamaño máximo de las listas
            int maxFilas = Math.max(fichas.size(), Math.max(programasFormacion.size(), Math.max(jornadasFormacion.size(), Math.max(nivelesFormacion.size(), Math.max(sedes.size(), areas.size())))));

            // Agregar cada fila con los datos correspondientes
            for (int i = 0; i < maxFilas; i++) {
                // Evitar que las listas cortas generen errores
                Integer ficha = (i < fichas.size()) ? fichas.get(i) : null;
                String programa = (i < programasFormacion.size()) ? programasFormacion.get(i) : "";
                String jornada = (i < jornadasFormacion.size()) ? jornadasFormacion.get(i) : "";
                String nivel = (i < nivelesFormacion.size()) ? nivelesFormacion.get(i) : "";
                String sede = (i < sedes.size()) ? sedes.get(i) : "";
                String area = (i < areas.size()) ? areas.get(i) : "";

                modeloTabla.addRow(new Object[]{
                        ficha,
                        programa,
                        jornada,
                        nivel,
                        sede,
                        area,
                        "Eliminar"  // Texto para el botón de eliminar
                });
            }

            // Asocia el ButtonRenderer y ButtonEditor con la columna del botón de eliminar
            FichasAsociadasTB.getColumnModel().getColumn(6).setCellRenderer(new ButtonColumnHelper.ButtonRenderer());
            FichasAsociadasTB.getColumnModel().getColumn(6).setCellEditor(new ButtonColumnHelper.ButtonEditor(new JCheckBox(), FichasAsociadasTB));

        } else {
            JOptionPane.showMessageDialog(null, "No se encontró el instructor con el documento proporcionado.");
        }
    }//GEN-LAST:event_BuscarDatosUsuarioActionPerformed

    private void ClaseFormacionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClaseFormacionCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClaseFormacionCBActionPerformed

    private void IDInstructorFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDInstructorFieldKeyTyped
                        char caracter = evt.getKeyChar();

        // Permitir solo números y la tecla de retroceso
        if (!Character.isDigit(caracter) && caracter != KeyEvent.VK_BACK_SPACE) {
            evt.consume();  // Evitar que se ingrese el carácter no válido
            JOptionPane.showMessageDialog(this, "Solo se permiten números.");
        }
    }//GEN-LAST:event_IDInstructorFieldKeyTyped

    private void ResultadoDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ResultadoDocumentoKeyTyped
                       char caracter = evt.getKeyChar();

        // Permitir solo números y la tecla de retroceso
        if (!Character.isDigit(caracter) && caracter != KeyEvent.VK_BACK_SPACE) {
            evt.consume();  // Evitar que se ingrese el carácter no válido
            JOptionPane.showMessageDialog(this, "Solo se permiten números.");
        }
    }//GEN-LAST:event_ResultadoDocumentoKeyTyped

    private void ResultadoTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ResultadoTelefonoKeyTyped
                        char caracter = evt.getKeyChar();

        // Permitir solo números y la tecla de retroceso
        if (!Character.isDigit(caracter) && caracter != KeyEvent.VK_BACK_SPACE) {
            evt.consume();  // Evitar que se ingrese el carácter no válido
            JOptionPane.showMessageDialog(this, "Solo se permiten números.");
        }
    }//GEN-LAST:event_ResultadoTelefonoKeyTyped

    private void ResultadoNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ResultadoNombresKeyTyped
                                  char caracter = evt.getKeyChar();

            // Permitir solo letras y las teclas de control (como backspace)
            if (!Character.isLetter(caracter) && caracter != KeyEvent.VK_BACK_SPACE) {
                evt.consume();  // Evitar que se ingrese el carácter no válido
                JOptionPane.showMessageDialog(this, "Solo se permiten letras.");
            }
    }//GEN-LAST:event_ResultadoNombresKeyTyped

    private void ResultadoApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ResultadoApellidosKeyTyped
                                  char caracter = evt.getKeyChar();

            // Permitir solo letras y las teclas de control (como backspace)
            if (!Character.isLetter(caracter) && caracter != KeyEvent.VK_BACK_SPACE) {
                evt.consume();  // Evitar que se ingrese el carácter no válido
                JOptionPane.showMessageDialog(this, "Solo se permiten letras.");
            }
    }//GEN-LAST:event_ResultadoApellidosKeyTyped

    private boolean fichaYaAsociada(int ficha) {
        DefaultTableModel modeloTabla = (DefaultTableModel) FichasAsociadasTB.getModel();
        int filas = modeloTabla.getRowCount();

        for (int i = 0; i < filas; i++) {
            int fichaEnTabla = (int) modeloTabla.getValueAt(i, 0); // La ficha está en la columna 0
            if (fichaEnTabla == ficha) {
                return true; // Ficha ya existe en la tabla
            }
        }
        return false; // Ficha no existe en la tabla
    }

    private void imprimirContenidoTabla() {
        try {
            DefaultTableModel modeloTabla = (DefaultTableModel) FichasAsociadasTB.getModel();
            int filas = modeloTabla.getRowCount();  // Número de filas
            int columnas = modeloTabla.getColumnCount();  // Número de columnas

            System.out.println("Contenido actual de la tabla:");

            // Recorre cada fila
            for (int i = 0; i < filas; i++) {
                StringBuilder fila = new StringBuilder();  // Utilizamos StringBuilder para construir cada fila
                // Recorre cada columna en la fila
                for (int j = 0; j < columnas; j++) {
                    Object value = modeloTabla.getValueAt(i, j);  // Obtiene el valor de la celda
                    fila.append(value != null ? value.toString() : "null").append(" ");  // Si el valor es null, muestra "null"
                }
                System.out.println(fila.toString().trim());  // Imprime la fila completa
            }

            // Si la tabla está vacía
            if (filas == 0) {
                System.out.println("La tabla está vacía.");
            }
        } catch (Exception e) {
            e.printStackTrace();  // Imprimir cualquier error que ocurra durante la impresión de la tabla
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AsociarFicha;
    private javax.swing.JComboBox<String> BarrioCB;
    private javax.swing.JButton BuscarDatosUsuario;
    private javax.swing.JComboBox<String> ClaseFormacionCB;
    private javax.swing.JButton ConfirmarRegistroUsuario;
    private javax.swing.JPanel CreateInstructorSubPanel;
    private javax.swing.JComboBox<String> DepartamentoCB;
    private javax.swing.JComboBox<String> DiaCB;
    private javax.swing.JComboBox<String> FichaCB;
    private javax.swing.JTable FichasAsociadasTB;
    private javax.swing.JComboBox<String> GeneroCB;
    private javax.swing.JTextField IDInstructorField;
    private javax.swing.JComboBox<String> MesCB;
    private javax.swing.JComboBox<String> MunicipioCB;
    private javax.swing.JTextField ResidenciaHolder;
    private javax.swing.JTextField ResultadoApellidos;
    private javax.swing.JTextField ResultadoArea;
    private javax.swing.JTextField ResultadoCorreo;
    private javax.swing.JTextField ResultadoDocumento;
    private javax.swing.JTextField ResultadoFechaHolder;
    private javax.swing.JTextField ResultadoJornadaFormacion;
    private javax.swing.JTextField ResultadoNivelFormacion;
    private javax.swing.JTextField ResultadoNombres;
    private javax.swing.JTextField ResultadoPass;
    private javax.swing.JTextField ResultadoProgramaFormacion;
    private javax.swing.JTextField ResultadoSede;
    private javax.swing.JTextField ResultadoTelefono;
    private javax.swing.JTextField ResultadoUsuario;
    private javax.swing.JComboBox<String> TipoDocCB;
    private javax.swing.JComboBox<String> YearCB;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
