/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.AdminFrames.AdminActionScreens.DeleteUserSubPanel;


import java.awt.event.KeyEvent;
import main.AdminFrames.AdminActionScreens.ModUserSubPanel.*;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Map;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.ArrayList;
import main.util.API_Actions.API_BuscarUsuario;

import main.util.API_AdminActions.API_Admin_UsersApplications.API_Admin_InstructorApplications;
import main.util.models.*;
import main.util.models.UsersModels.InstructorModel;

/**
 *
 * @author usuario
 */
public class DelInstructorSubPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateInstructorSubPanel
     */
    DefaultComboBoxModel<String> yearModel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> mesModel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> diaModel = new DefaultComboBoxModel<>();
    DefaultTableModel modeloTabla = new DefaultTableModel(
            new Object[] {"Ficha", "Jornada de Formación"},
            0  // Número de filas iniciales
    );

    public DelInstructorSubPanel() {
        initComponents();
        aditionalConfig();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateInstructorSubPanel = new javax.swing.JPanel();
        ConfirmareliminarInstructor = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ResidenciaHolder = new javax.swing.JTextField();
        ResultadoFechaHolder = new javax.swing.JTextField();
        DiaCB = new javax.swing.JComboBox<>();
        MesCB = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        ResultadoNombres = new javax.swing.JTextField();
        ResultadoPass = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        GeneroCB = new javax.swing.JComboBox<>();
        ResultadoUsuario = new javax.swing.JTextField();
        TipoDocCB = new javax.swing.JComboBox<>();
        ResultadoDocumento = new javax.swing.JTextField();
        ResultadoApellidos = new javax.swing.JTextField();
        MunicipioCB = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        BarrioCB = new javax.swing.JComboBox<>();
        ResultadoCorreo = new javax.swing.JTextField();
        DepartamentoCB = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        YearCB = new javax.swing.JComboBox<>();
        ResultadoTelefono = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IDInstructorField = new javax.swing.JTextField();
        BuscarDatosUsuario = new javax.swing.JButton();
        HabilitarInstructor = new javax.swing.JButton();

        CreateInstructorSubPanel.setBackground(new java.awt.Color(255, 255, 255));

        ConfirmareliminarInstructor.setBackground(new java.awt.Color(0, 34, 64));
        ConfirmareliminarInstructor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmareliminarInstructor.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmareliminarInstructor.setText("Deshabilitar Instructor");
        ConfirmareliminarInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmareliminarInstructorActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Usuario");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Genero");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Tipo de documento");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Apellidos");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Nombres");

        ResidenciaHolder.setEditable(false);
        ResidenciaHolder.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResidenciaHolder.setForeground(new java.awt.Color(0, 0, 0));
        ResidenciaHolder.setFocusable(false);

        ResultadoFechaHolder.setEditable(false);
        ResultadoFechaHolder.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResultadoFechaHolder.setForeground(new java.awt.Color(0, 0, 0));
        ResultadoFechaHolder.setFocusable(false);

        DiaCB.setForeground(new java.awt.Color(0, 0, 0));
        DiaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DiaCB.setEnabled(false);
        DiaCB.setFocusable(false);
        DiaCB.setPreferredSize(new java.awt.Dimension(64, 28));
        DiaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaCBActionPerformed(evt);
            }
        });

        MesCB.setForeground(new java.awt.Color(0, 0, 0));
        MesCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MesCB.setEnabled(false);
        MesCB.setFocusable(false);
        MesCB.setPreferredSize(new java.awt.Dimension(64, 28));
        MesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesCBActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Correo");

        ResultadoNombres.setEditable(false);
        ResultadoNombres.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResultadoNombres.setForeground(new java.awt.Color(0, 0, 0));
        ResultadoNombres.setFocusable(false);
        ResultadoNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ResultadoNombresKeyTyped(evt);
            }
        });

        ResultadoPass.setEditable(false);
        ResultadoPass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResultadoPass.setForeground(new java.awt.Color(0, 0, 0));
        ResultadoPass.setFocusable(false);
        ResultadoPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoPassActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Contraseña");

        GeneroCB.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        GeneroCB.setForeground(new java.awt.Color(0, 0, 0));
        GeneroCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        GeneroCB.setEnabled(false);
        GeneroCB.setFocusable(false);
        GeneroCB.setPreferredSize(new java.awt.Dimension(64, 28));
        GeneroCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroCBActionPerformed(evt);
            }
        });

        ResultadoUsuario.setEditable(false);
        ResultadoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResultadoUsuario.setForeground(new java.awt.Color(0, 0, 0));
        ResultadoUsuario.setFocusable(false);

        TipoDocCB.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TipoDocCB.setForeground(new java.awt.Color(0, 0, 0));
        TipoDocCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TipoDocCB.setEnabled(false);
        TipoDocCB.setFocusable(false);
        TipoDocCB.setPreferredSize(new java.awt.Dimension(64, 28));
        TipoDocCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDocCBActionPerformed(evt);
            }
        });

        ResultadoDocumento.setEditable(false);
        ResultadoDocumento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResultadoDocumento.setForeground(new java.awt.Color(0, 0, 0));
        ResultadoDocumento.setFocusable(false);
        ResultadoDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ResultadoDocumentoKeyTyped(evt);
            }
        });

        ResultadoApellidos.setEditable(false);
        ResultadoApellidos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResultadoApellidos.setForeground(new java.awt.Color(0, 0, 0));
        ResultadoApellidos.setFocusable(false);

        MunicipioCB.setForeground(new java.awt.Color(0, 0, 0));
        MunicipioCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MunicipioCB.setEnabled(false);
        MunicipioCB.setFocusable(false);
        MunicipioCB.setPreferredSize(new java.awt.Dimension(64, 28));
        MunicipioCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MunicipioCBActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Documento");

        BarrioCB.setForeground(new java.awt.Color(0, 0, 0));
        BarrioCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BarrioCB.setEnabled(false);
        BarrioCB.setFocusable(false);
        BarrioCB.setPreferredSize(new java.awt.Dimension(64, 28));
        BarrioCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarrioCBActionPerformed(evt);
            }
        });

        ResultadoCorreo.setEditable(false);
        ResultadoCorreo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResultadoCorreo.setForeground(new java.awt.Color(0, 0, 0));
        ResultadoCorreo.setFocusable(false);

        DepartamentoCB.setForeground(new java.awt.Color(0, 0, 0));
        DepartamentoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DepartamentoCB.setEnabled(false);
        DepartamentoCB.setFocusable(false);
        DepartamentoCB.setPreferredSize(new java.awt.Dimension(64, 28));
        DepartamentoCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartamentoCBActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Residencia");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Telefono");

        YearCB.setForeground(new java.awt.Color(0, 0, 0));
        YearCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        YearCB.setEnabled(false);
        YearCB.setFocusable(false);
        YearCB.setPreferredSize(new java.awt.Dimension(64, 28));
        YearCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearCBActionPerformed(evt);
            }
        });

        ResultadoTelefono.setEditable(false);
        ResultadoTelefono.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ResultadoTelefono.setForeground(new java.awt.Color(0, 0, 0));
        ResultadoTelefono.setFocusable(false);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Fecha de Nacimiento");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Documento del usuario");

        IDInstructorField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        IDInstructorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDInstructorFieldActionPerformed(evt);
            }
        });
        IDInstructorField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDInstructorFieldKeyTyped(evt);
            }
        });

        BuscarDatosUsuario.setBackground(new java.awt.Color(57, 169, 0));
        BuscarDatosUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BuscarDatosUsuario.setForeground(new java.awt.Color(255, 255, 255));
        BuscarDatosUsuario.setText("Buscar");
        BuscarDatosUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarDatosUsuarioActionPerformed(evt);
            }
        });

        HabilitarInstructor.setBackground(new java.awt.Color(57, 169, 0));
        HabilitarInstructor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        HabilitarInstructor.setForeground(new java.awt.Color(255, 255, 255));
        HabilitarInstructor.setText("Habilitar Instructor");
        HabilitarInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabilitarInstructorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreateInstructorSubPanelLayout = new javax.swing.GroupLayout(CreateInstructorSubPanel);
        CreateInstructorSubPanel.setLayout(CreateInstructorSubPanelLayout);
        CreateInstructorSubPanelLayout.setHorizontalGroup(
            CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HabilitarInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addGap(120, 120, 120)
                            .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TipoDocCB, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ResultadoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ResultadoNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ResultadoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                            .addComponent(IDInstructorField, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BuscarDatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                            .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel30)
                                .addComponent(jLabel29)
                                .addComponent(jLabel18)
                                .addComponent(jLabel23)
                                .addComponent(jLabel25))
                            .addGap(56, 56, 56)
                            .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ResultadoCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ResultadoTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CreateInstructorSubPanelLayout.createSequentialGroup()
                                    .addComponent(YearCB, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MesCB, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DiaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ResultadoFechaHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CreateInstructorSubPanelLayout.createSequentialGroup()
                                    .addComponent(DepartamentoCB, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MunicipioCB, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BarrioCB, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ResidenciaHolder))
                                .addComponent(GeneroCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                            .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22)
                                .addComponent(jLabel21)
                                .addComponent(jLabel20)
                                .addComponent(jLabel27)
                                .addComponent(jLabel28))
                            .addGap(67, 67, 67)
                            .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ResultadoPass, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ResultadoUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(ConfirmareliminarInstructor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        CreateInstructorSubPanelLayout.setVerticalGroup(
            CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HabilitarInstructor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDInstructorField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResultadoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(9, 9, 9)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19))
                    .addGroup(CreateInstructorSubPanelLayout.createSequentialGroup()
                        .addComponent(ResultadoPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ResultadoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoDocCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResultadoNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResultadoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(YearCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MesCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DiaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ResultadoFechaHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GeneroCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResultadoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(ResultadoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addGroup(CreateInstructorSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DepartamentoCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MunicipioCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BarrioCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ResidenciaHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(ConfirmareliminarInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateInstructorSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateInstructorSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
        public void aditionalConfig(){
            try {
                ButtonStyler buttonStyler = new ButtonStyler();
                yearModel.addElement("Seleccionar Año");
                llenarYear(yearModel);
                mesModel.addElement("Seleccionar Mes");
                diaModel.addElement("Seleccionar Día");
                ComboBoxModels CBModels = new ComboBoxModels();
                TipoDocCB.setModel(CBModels.generarComboBoxModelPorTipo("TipoDocumento"));
                GeneroCB.setModel(CBModels.generarComboBoxModelPorTipo("Genero"));
                MunicipioCB.setModel(CBModels.generarComboBoxModelPorTipo("Municipios"));
                DepartamentoCB.setModel(CBModels.generarComboBoxModelPorTipo("Departamentos"));
                BarrioCB.setModel(CBModels.generarComboBoxModelPorTipo("Barrios"));
                YearCB.setModel(yearModel);
                MesCB.setModel(mesModel);
                DiaCB.setModel(diaModel);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
        
         private void llenarYear(DefaultComboBoxModel<String> anhoModel) {
        int anhoActual = Calendar.getInstance().get(Calendar.YEAR);
        for (int i = anhoActual; i > anhoActual - 100; i--) {
            anhoModel.addElement(String.valueOf(i));
        }
    }

    public void llenarMeses() {
        mesModel.removeAllElements();
        mesModel.addElement("Seleccionar Mes");
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
                "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        for (String mes : meses) {
            mesModel.addElement(mes);
        }
    }

    private void llenarDias(DefaultComboBoxModel<String> diaModel, int anho, int mes) {
        diaModel.removeAllElements();
        diaModel.addElement("Seleccionar Día");
        int diasEnMes = obtenerDiasDelMes(anho, mes);
        for (int i = 1; i <= diasEnMes; i++) {
            diaModel.addElement(String.valueOf(i));
        }
    }

    private int obtenerDiasDelMes(int anho, int mes) {
        switch (mes) {
            case 1: case 3: case 5: case 7: case 8: case 10: case 12:
                return 31;
            case 4: case 6: case 9: case 11:
                return 30;
            case 2:
                return (anho % 4 == 0 && (anho % 100 != 0 || anho % 400 == 0)) ? 29 : 28;
            default:
                return 30;
        }
    }

    private int obtenerNumeroMes(String mesSeleccionado) {
        switch (mesSeleccionado) {
            case "Enero": return 1;
            case "Febrero": return 2;
            case "Marzo": return 3;
            case "Abril": return 4;
            case "Mayo": return 5;
            case "Junio": return 6;
            case "Julio": return 7;
            case "Agosto": return 8;
            case "Septiembre": return 9;
            case "Octubre": return 10;
            case "Noviembre": return 11;
            case "Diciembre": return 12;
            default: return -1; // En caso de error
        }
    }

    private void actualizarFecha() {
        String anhoSeleccionado = (String) YearCB.getSelectedItem();
        String mesSeleccionado = (String) MesCB.getSelectedItem();
        String diaSeleccionado = (String) DiaCB.getSelectedItem();

        // Comprobar si los tres elementos han sido seleccionados correctamente
        if (anhoSeleccionado != null && !anhoSeleccionado.equals("Seleccionar Año") &&
                mesSeleccionado != null && !mesSeleccionado.equals("Seleccionar Mes") &&
                diaSeleccionado != null && !diaSeleccionado.equals("Seleccionar Día")) {

            // Convertir el nombre del mes a su número usando obtenerNumeroMes()
            int numeroMes = obtenerNumeroMes(mesSeleccionado);
            String mesConFormato = (numeroMes < 10 ? "0" : "") + numeroMes; // Formatear el mes con cero si es necesario
            String diaConFormato = (Integer.parseInt(diaSeleccionado) < 10 ? "0" : "") + diaSeleccionado; // Formatear el día con cero si es necesario

            // Mostrar la fecha en formato "yyyy-MM-dd"
            ResultadoFechaHolder.setText(anhoSeleccionado + "-" + mesConFormato + "-" + diaConFormato);
        } else {
            // Si alguno no está seleccionado, mostrar el campo vacío o parcialmente seleccionado
            String fechaParcial = "";
            if (anhoSeleccionado != null && !anhoSeleccionado.equals("Seleccionar Año")) {
                fechaParcial += anhoSeleccionado;
            }
            if (mesSeleccionado != null && !mesSeleccionado.equals("Seleccionar Mes")) {
                int numeroMes = obtenerNumeroMes(mesSeleccionado);
                String mesConFormato = (numeroMes < 10 ? "0" : "") + numeroMes; // Formatear el mes con cero si es necesario
                if (!fechaParcial.isEmpty()) {
                    fechaParcial += "-";  // Solo añadir el guion si ya hay algo en la fecha parcial
                }
                fechaParcial += mesConFormato;
            }
            if (diaSeleccionado != null && !diaSeleccionado.equals("Seleccionar Día")) {
                String diaConFormato = (Integer.parseInt(diaSeleccionado) < 10 ? "0" : "") + diaSeleccionado; // Formatear el día con cero si es necesario
                if (!fechaParcial.isEmpty()) {
                    fechaParcial += "-";  // Solo añadir el guion si ya hay algo en la fecha parcial
                }
                fechaParcial += diaConFormato;
            }
            ResultadoFechaHolder.setText(fechaParcial); // Mostrar la selección parcial
        }
    }
    
    private void actualizarResidencia() {
        String departamentoSeleccionado = (String) DepartamentoCB.getSelectedItem();
        String municipioSeleccionado = (String) MunicipioCB.getSelectedItem();
        String barrioSeleccionado = (String) BarrioCB.getSelectedItem();

        // Comprobar si los tres elementos han sido seleccionados correctamente
        if (departamentoSeleccionado != null && !departamentoSeleccionado.equals("Seleccionar...") &&
            municipioSeleccionado != null && !municipioSeleccionado.equals("Seleccionar...") &&
            barrioSeleccionado != null && !barrioSeleccionado.equals("Seleccionar...")) {

            // Mostrar la residencia en formato "Departamento - Municipio - Barrio"
            ResidenciaHolder.setText(departamentoSeleccionado + " - " + municipioSeleccionado + " - " + barrioSeleccionado);
        } else {
            // Si alguno no está seleccionado, mostrar el campo parcial
            String residenciaParcial = "";
            if (departamentoSeleccionado != null && !departamentoSeleccionado.equals("Seleccionar...")) {
                residenciaParcial += departamentoSeleccionado;
            }
            if (municipioSeleccionado != null && !municipioSeleccionado.equals("Seleccionar...")) {
                if (!residenciaParcial.isEmpty()) {
                    residenciaParcial += " - ";  // Solo añadir el separador si hay un valor previo
                }
                residenciaParcial += municipioSeleccionado;
            }
            if (barrioSeleccionado != null && !barrioSeleccionado.equals("Seleccionar...")) {
                if (!residenciaParcial.isEmpty()) {
                    residenciaParcial += " - ";  // Solo añadir el separador si hay un valor previo
                }
                residenciaParcial += barrioSeleccionado;
            }
            ResidenciaHolder.setText(residenciaParcial);  // Mostrar la selección parcial
        }
    }

    private void ConfirmareliminarInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmareliminarInstructorActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea inhabilitar al instructor?", "Confirmación", JOptionPane.YES_NO_CANCEL_OPTION);

        switch (respuesta) {
            case JOptionPane.YES_OPTION -> {
                try {
                    API_BuscarUsuario desHabilitarInstructor = new API_BuscarUsuario();
                    desHabilitarInstructor.inhabilitarInstructor(ResultadoDocumento.getText());
//                    API_Admin_InstructorApplications eliminarInstructor = new API_Admin_InstructorApplications();
//                    eliminarInstructor.DeleteInstructor(ResultadoDocumento.getText());

                    // Limpiar formulario después de la actualización
                    limpiarFormularioInstructor();

                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error al eliminar los datos del instructor: " + e.getMessage());
                }
            }

            case JOptionPane.NO_OPTION, JOptionPane.CANCEL_OPTION -> {
                // Acción para NO o CANCELAR
            }
        }
    }//GEN-LAST:event_ConfirmareliminarInstructorActionPerformed


    private void limpiarFormularioInstructor() {
        ResultadoUsuario.setText("");
        ResultadoPass.setText("");
        ResultadoDocumento.setText("");
        ResultadoNombres.setText("");
        ResultadoApellidos.setText("");
        ResultadoTelefono.setText("");
        ResultadoCorreo.setText("");
        ResidenciaHolder.setText("");
        ResultadoFechaHolder.setText("");

        // Restablecer JComboBoxes
        TipoDocCB.setSelectedIndex(0);  // Asumiendo que el índice 0 es "Seleccionar..."
        YearCB.setSelectedIndex(0);
        MesCB.setSelectedIndex(0);
        MesCB.setEnabled(false);
        DiaCB.setSelectedIndex(0);
        DiaCB.setEnabled(false);
        GeneroCB.setSelectedIndex(0);  // Asumiendo que el índice 0 es "Seleccionar..."
        DepartamentoCB.setSelectedIndex(0);
        MunicipioCB.setSelectedIndex(0);
        MunicipioCB.setEnabled(false);
        BarrioCB.setSelectedIndex(0);
        BarrioCB.setEnabled(false);

        modeloTabla.setRowCount(0);  // Vaciar todas las filas de la tabla

        // Otros campos de tipo JComboBox o componentes pueden ser reseteados aquí
    }

    private void DiaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaCBActionPerformed
        String diaSeleccionado = (String) DiaCB.getSelectedItem();

        if (diaSeleccionado != null && !diaSeleccionado.equals("Seleccionar Día")) {
            actualizarFecha();  // Llamada al método para actualizar el TextField
        }
    }//GEN-LAST:event_DiaCBActionPerformed

    private void MesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesCBActionPerformed
        String mesSeleccionado = (String) MesCB.getSelectedItem();

        // Verificamos si es "Seleccionar Mes"
        if (mesSeleccionado == null || mesSeleccionado.equals("Seleccionar Mes")) {
            diaModel.removeAllElements();   // Limpiar los días
            diaModel.addElement("Seleccionar Día");  // Volver a poner la opción por defecto
            DiaCB.setEnabled(false);  // Deshabilitar el ComboBox de Día
        } else {
            // Si se selecciona un mes válido, llenar los días
            int anho = Integer.parseInt((String) YearCB.getSelectedItem());
            int numeroMes = obtenerNumeroMes(mesSeleccionado);  // Obtener el número correcto del mes

            // Llenar los días en el ComboBox de Día
            llenarDias(diaModel, anho, numeroMes);

        }

        actualizarFecha();  // Actualizar el TextField FechaHolder
    }//GEN-LAST:event_MesCBActionPerformed

    private void ResultadoPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoPassActionPerformed

    private void GeneroCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroCBActionPerformed

    private void TipoDocCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDocCBActionPerformed

    }//GEN-LAST:event_TipoDocCBActionPerformed

    private void MunicipioCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MunicipioCBActionPerformed
        String municipioSeleccionado = (String) MunicipioCB.getSelectedItem();

        if (municipioSeleccionado != null && !municipioSeleccionado.equals("Seleccionar...")) {

        } else {
            BarrioCB.setEnabled(false);  // Deshabilitar el ComboBox de Barrio si no se selecciona un municipio válido
            BarrioCB.setSelectedItem("Seleccionar...");   // Situar el Barrio en "Seleccionar..."
        }

        actualizarResidencia();  // Actualizar el ResidenciaHolder
    }//GEN-LAST:event_MunicipioCBActionPerformed

    private void BarrioCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarrioCBActionPerformed
        actualizarResidencia();  // Llamar al método para actualizar el ResidenciaHolder
    }//GEN-LAST:event_BarrioCBActionPerformed

    private void DepartamentoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartamentoCBActionPerformed
        String departamentoSeleccionado = (String) DepartamentoCB.getSelectedItem();

        if (departamentoSeleccionado != null && !departamentoSeleccionado.equals("Seleccionar...")) {
            BarrioCB.setEnabled(false);    // Deshabilitar el ComboBox de Barrio hasta que se seleccione un municipio
            BarrioCB.setSelectedItem("Seleccionar...");  // Situar el Barrio en "Seleccionar..."
        } else {
            // Si no se ha seleccionado un departamento válido, deshabilitar Municipio y Barrio
            MunicipioCB.setEnabled(false);
            BarrioCB.setEnabled(false);
            MunicipioCB.setSelectedItem("Seleccionar...");  // Situar el Municipio en "Seleccionar..."
            BarrioCB.setSelectedItem("Seleccionar...");     // Situar el Barrio en "Seleccionar..."
        }

        actualizarResidencia();  // Actualizar el ResidenciaHolder
    }//GEN-LAST:event_DepartamentoCBActionPerformed

    private void YearCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearCBActionPerformed
        String YearSeleccionado = (String) YearCB.getSelectedItem();

        // Verificamos si es "Seleccionar Año"
        if (YearSeleccionado == null || YearSeleccionado.equals("Seleccionar Año")) {
            mesModel.removeAllElements();   // Limpiar los meses
            mesModel.addElement("Seleccionar Mes");  // Volver a poner la opción por defecto
            MesCB.setEnabled(false);  // Deshabilitar el ComboBox de Mes

            diaModel.removeAllElements();   // Limpiar los días
            diaModel.addElement("Seleccionar Día");  // Volver a poner la opción por defecto
            DiaCB.setEnabled(false);  // Deshabilitar el ComboBox de Día
        } else {
            // Si se selecciona un año válido, llenar los meses
            llenarMeses();  // Llenar los meses
            DiaCB.removeAllItems();  // Limpiar los días por si acaso
        }

        actualizarFecha();  // Actualizar el TextField FechaHolder
    }//GEN-LAST:event_YearCBActionPerformed

    private void IDInstructorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDInstructorFieldActionPerformed
        BuscarDatosUsuario.doClick();
    }//GEN-LAST:event_IDInstructorFieldActionPerformed

    private void BuscarDatosUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarDatosUsuarioActionPerformed
        // Crea una nueva instancia de API_BuscarUsuario para buscar un instructor
        API_BuscarUsuario buscarInstructor = new API_BuscarUsuario();

        // Intenta buscar el instructor en la base de datos usando el documento ingresado
        InstructorModel instructor = buscarInstructor.buscarInstructorPorDocumento(IDInstructorField.getText());

        if (instructor != null) {
            // Rellenar los campos con los datos del instructor

            // Nombre de usuario
            ResultadoUsuario.setText(instructor.getUser());

            // Documento y tipo de documento
            ResultadoDocumento.setText(instructor.getDocumento());
            TipoDocCB.setSelectedItem(instructor.getTipoDocumento());

            // Nombres y apellidos
            ResultadoNombres.setText(instructor.getNombres());
            ResultadoApellidos.setText(instructor.getApellidos());

            // Fecha de nacimiento (convertir java.sql.Date a String en formato "yyyy-MM-dd")
            Date fechaNacimiento = instructor.getFechaNacimiento();
            if (fechaNacimiento != null) {
                LocalDate fecha = fechaNacimiento.toLocalDate();
                int anho = fecha.getYear();
                int mes = fecha.getMonthValue();
                int dia = fecha.getDayOfMonth();

                // Setear YearCB, MesCB, DiaCB
                YearCB.setSelectedItem(String.valueOf(anho));

                String[] mesesNombres = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
                String nombreMes = mesesNombres[mes - 1];
                MesCB.setSelectedItem(nombreMes);

                // Setear DiaCB
                DiaCB.setSelectedItem(String.valueOf(dia));
            }

            // Género
            GeneroCB.setSelectedItem(instructor.getGenero());

            // Correo y teléfono
            ResultadoCorreo.setText(instructor.getCorreo());
            ResultadoTelefono.setText(instructor.getTelefono());

            // Residencia
            String[] residencia = instructor.getResidencia().split(" - ");
            if (residencia.length == 3) {
                DepartamentoCB.setSelectedItem(residencia[0]);
                MunicipioCB.setSelectedItem(residencia[1]);
                BarrioCB.setSelectedItem(residencia[2]);
            }


        } else {
            JOptionPane.showMessageDialog(null, "No se encontró el instructor con el documento proporcionado.");
        }
    }//GEN-LAST:event_BuscarDatosUsuarioActionPerformed

    private void IDInstructorFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDInstructorFieldKeyTyped
                        char caracter = evt.getKeyChar();

        // Permitir solo números y la tecla de retroceso
        if (!Character.isDigit(caracter) && caracter != KeyEvent.VK_BACK_SPACE) {
            evt.consume();  // Evitar que se ingrese el carácter no válido
            JOptionPane.showMessageDialog(this, "Solo se permiten números.");
        }
    }//GEN-LAST:event_IDInstructorFieldKeyTyped

    private void ResultadoDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ResultadoDocumentoKeyTyped
                char caracter = evt.getKeyChar();

        // Permitir solo números y la tecla de retroceso
        if (!Character.isDigit(caracter) && caracter != KeyEvent.VK_BACK_SPACE) {
            evt.consume();  // Evitar que se ingrese el carácter no válido
            JOptionPane.showMessageDialog(this, "Solo se permiten números.");
        }
    }//GEN-LAST:event_ResultadoDocumentoKeyTyped

    private void ResultadoNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ResultadoNombresKeyTyped
                                  char caracter = evt.getKeyChar();

            // Permitir solo letras y las teclas de control (como backspace)
            if (!Character.isLetter(caracter) && caracter != KeyEvent.VK_BACK_SPACE) {
                evt.consume();  // Evitar que se ingrese el carácter no válido
                JOptionPane.showMessageDialog(this, "Solo se permiten letras.");
            }
    }//GEN-LAST:event_ResultadoNombresKeyTyped

    private void HabilitarInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabilitarInstructorActionPerformed
        API_BuscarUsuario api = new API_BuscarUsuario();
        String documento = null;

        while (true) {
            // Paso 1: Solicitar el documento
            documento = JOptionPane.showInputDialog(this, "Ingrese el documento del Instructor a habilitar:", "Habilitar Instructor", JOptionPane.QUESTION_MESSAGE);

            // Verificar si el usuario canceló la operación
            if (documento == null) {
                // Usuario canceló
                return;
            }

            documento = documento.trim();

            // Paso 2: Validar el documento (solo números y no vacío)
            if (documento.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El documento no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
                continue;
            }

            if (!documento.matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "El documento solo debe contener números.", "Error", JOptionPane.ERROR_MESSAGE);
                continue;
            }

            // Paso 3: Confirmar la habilitación
            int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea habilitar al Instructor con documento " + documento + "?", "Confirmar Habilitación", JOptionPane.YES_NO_OPTION);

            if (confirm != JOptionPane.YES_OPTION) {
                // Usuario no confirmó
                return;
            }

            // Paso 4: Solicitar nuevamente el documento para confirmar
            String documentoConfirmacion = JOptionPane.showInputDialog(this, "Por favor, reingrese el documento para confirmar:", "Confirmar Documento", JOptionPane.QUESTION_MESSAGE);

            if (documentoConfirmacion == null) {
                // Usuario canceló
                return;
            }

            documentoConfirmacion = documentoConfirmacion.trim();

            // Validar el documento de confirmación
            if (!documentoConfirmacion.equals(documento)) {
                JOptionPane.showMessageDialog(this, "El documento no coincide. Operación cancelada.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Paso 5: Enviar la solicitud de habilitación
            boolean resultado = api.habilitarInstructor(documento);

            if (resultado) {
                
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo habilitar al Instructor. Verifique que el documento sea correcto y que el Instructor exista.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            // Salir del bucle después de intentar la operación
            break;
        }
    }//GEN-LAST:event_HabilitarInstructorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BarrioCB;
    private javax.swing.JButton BuscarDatosUsuario;
    private javax.swing.JButton ConfirmareliminarInstructor;
    private javax.swing.JPanel CreateInstructorSubPanel;
    private javax.swing.JComboBox<String> DepartamentoCB;
    private javax.swing.JComboBox<String> DiaCB;
    private javax.swing.JComboBox<String> GeneroCB;
    private javax.swing.JButton HabilitarInstructor;
    private javax.swing.JTextField IDInstructorField;
    private javax.swing.JComboBox<String> MesCB;
    private javax.swing.JComboBox<String> MunicipioCB;
    private javax.swing.JTextField ResidenciaHolder;
    private javax.swing.JTextField ResultadoApellidos;
    private javax.swing.JTextField ResultadoCorreo;
    private javax.swing.JTextField ResultadoDocumento;
    private javax.swing.JTextField ResultadoFechaHolder;
    private javax.swing.JTextField ResultadoNombres;
    private javax.swing.JTextField ResultadoPass;
    private javax.swing.JTextField ResultadoTelefono;
    private javax.swing.JTextField ResultadoUsuario;
    private javax.swing.JComboBox<String> TipoDocCB;
    private javax.swing.JComboBox<String> YearCB;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
