/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.AdminFrames.AdminActionScreens;

import java.awt.*;
import java.awt.event.ItemEvent;

import main.AdminFrames.AdminActionScreens.CreateUserSubPanel.CreateAprendizSubPanel;
import main.AdminFrames.AdminActionScreens.CreateUserSubPanel.CreateInstructorSubPanel;


/**
 *
 * @author Propietario
 */
public class CrearUsuarioPanel extends javax.swing.JPanel {

    /**
     * Creates new form CrearUsuarioPanel
     */

    private CardLayout cardLayout;
    public CrearUsuarioPanel() {
        initComponents();
        initCardLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InstructorCheck = new javax.swing.JToggleButton();
        AprendizCheck = new javax.swing.JToggleButton();
        Panel_RegistrarDatos = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 34, 64));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 34, 64));
        jLabel1.setText("Que tipo de usuario desea registrar?");

        InstructorCheck.setBackground(new java.awt.Color(255, 255, 255));
        InstructorCheck.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        InstructorCheck.setForeground(new java.awt.Color(0, 0, 0));
        InstructorCheck.setText("Instructor");
        InstructorCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                InstructorCheckItemStateChanged(evt);
            }
        });
        InstructorCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructorCheckActionPerformed(evt);
            }
        });

        AprendizCheck.setBackground(new java.awt.Color(255, 255, 255));
        AprendizCheck.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        AprendizCheck.setForeground(new java.awt.Color(0, 0, 0));
        AprendizCheck.setText("Aprendiz");
        AprendizCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AprendizCheckItemStateChanged(evt);
            }
        });

        Panel_RegistrarDatos.setBackground(new java.awt.Color(255, 255, 255));
        Panel_RegistrarDatos.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout Panel_RegistrarDatosLayout = new javax.swing.GroupLayout(Panel_RegistrarDatos);
        Panel_RegistrarDatos.setLayout(Panel_RegistrarDatosLayout);
        Panel_RegistrarDatosLayout.setHorizontalGroup(
            Panel_RegistrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 971, Short.MAX_VALUE)
        );
        Panel_RegistrarDatosLayout.setVerticalGroup(
            Panel_RegistrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_RegistrarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(InstructorCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AprendizCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AprendizCheck)
                    .addComponent(InstructorCheck))
                .addGap(8, 8, 8)
                .addComponent(Panel_RegistrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1034, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initCardLayout() {
        cardLayout = new CardLayout();
        Panel_RegistrarDatos.setLayout(cardLayout);

        CreateAprendizSubPanel apredizPanel = new CreateAprendizSubPanel();
        CreateInstructorSubPanel instructorPanel = new CreateInstructorSubPanel();
        // Agrega los paneles al CardLayout
        Panel_RegistrarDatos.add(apredizPanel, "AprendizPanel");
        Panel_RegistrarDatos.add(instructorPanel, "InstructorPanel");

        // Muestra el panel del aprendiz por defecto (opcional)
        cardLayout.show(Panel_RegistrarDatos, "AprendizPanel");
    }

    
    private void InstructorCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_InstructorCheckItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // Cambia el color de fondo a verde para indicar que está activo
            InstructorCheck.setBackground(Color.decode("#39A900"));
            InstructorCheck.setForeground(Color.WHITE);

            // Cambiar al panel del instructor
            cardLayout.show(Panel_RegistrarDatos, "InstructorPanel");

            // Desactivar el botón de aprendiz y restaurar su estilo
            AprendizCheck.setSelected(false);
            AprendizCheck.setBackground(Color.WHITE);
            AprendizCheck.setForeground(Color.BLACK);
        } else {
            // Restaurar el color de fondo cuando no está seleccionado
            InstructorCheck.setBackground(Color.WHITE);
            InstructorCheck.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_InstructorCheckItemStateChanged

    private void InstructorCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructorCheckActionPerformed

    }//GEN-LAST:event_InstructorCheckActionPerformed

    private void AprendizCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AprendizCheckItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // Cambia el color de fondo a verde para indicar que está activo
            AprendizCheck.setBackground(Color.decode("#39A900"));
            AprendizCheck.setForeground(Color.WHITE);

            // Cambiar al panel del aprendiz
            cardLayout.show(Panel_RegistrarDatos, "AprendizPanel");

            // Desactivar el botón de instructor y restaurar su estilo
            InstructorCheck.setSelected(false);
            InstructorCheck.setBackground(Color.WHITE);
            InstructorCheck.setForeground(Color.BLACK);
        } else {
            // Restaurar el color de fondo cuando no está seleccionado
            AprendizCheck.setBackground(Color.WHITE);
            AprendizCheck.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_AprendizCheckItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AprendizCheck;
    private javax.swing.JToggleButton InstructorCheck;
    private javax.swing.JPanel Panel_RegistrarDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
