/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.AdminFrames.AdminActionScreens;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ItemEvent;
import javax.swing.*;
import main.AdminFrames.AdminActionScreens.ModUserSubPanel.ModAprendizSubPanel;
import main.AdminFrames.AdminActionScreens.ModUserSubPanel.ModInstructorSubPanel;
import main.LoginFrame;



/**
 *
 * @author Propietario
 */
public class ModificarUsuarioPanel extends javax.swing.JPanel {

    /**
     * Creates new form ModificarUsuarioPanel
     */
    private CardLayout cardLayout;
    public ModificarUsuarioPanel() throws Exception {
        initComponents();
        initCardLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MainPanelModUser = new javax.swing.JPanel();
        InstructorCheck = new javax.swing.JToggleButton();
        AprendizCheck = new javax.swing.JToggleButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout MainPanelModUserLayout = new javax.swing.GroupLayout(MainPanelModUser);
        MainPanelModUser.setLayout(MainPanelModUserLayout);
        MainPanelModUserLayout.setHorizontalGroup(
            MainPanelModUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        MainPanelModUserLayout.setVerticalGroup(
            MainPanelModUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );

        InstructorCheck.setBackground(new java.awt.Color(255, 255, 255));
        InstructorCheck.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        InstructorCheck.setForeground(new java.awt.Color(0, 0, 0));
        InstructorCheck.setText("Instructor");
        InstructorCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                InstructorCheckItemStateChanged(evt);
            }
        });
        InstructorCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructorCheckActionPerformed(evt);
            }
        });

        AprendizCheck.setBackground(new java.awt.Color(255, 255, 255));
        AprendizCheck.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        AprendizCheck.setForeground(new java.awt.Color(0, 0, 0));
        AprendizCheck.setText("Aprendiz");
        AprendizCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AprendizCheckItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MainPanelModUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(InstructorCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AprendizCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InstructorCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AprendizCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(MainPanelModUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InstructorCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_InstructorCheckItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // Cambia el color de fondo a verde para indicar que está activo
            InstructorCheck.setBackground(Color.decode("#39A900"));
            InstructorCheck.setForeground(Color.WHITE);

            // Cambiar al panel del instructor
            cardLayout.show(MainPanelModUser, "InstructorPanel");

            // Desactivar el botón de aprendiz y restaurar su estilo
            AprendizCheck.setSelected(false);
            AprendizCheck.setBackground(Color.WHITE);
            AprendizCheck.setForeground(Color.BLACK);
        } else {
            // Restaurar el color de fondo cuando no está seleccionado
            InstructorCheck.setBackground(Color.WHITE);
            InstructorCheck.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_InstructorCheckItemStateChanged

    private void InstructorCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructorCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstructorCheckActionPerformed

    private void AprendizCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AprendizCheckItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // Cambia el color de fondo a verde para indicar que está activo
            AprendizCheck.setBackground(Color.decode("#39A900"));
            AprendizCheck.setForeground(Color.WHITE);

            // Cambiar al panel del aprendiz
            cardLayout.show(MainPanelModUser, "AprendizPanel");

            // Desactivar el botón de instructor y restaurar su estilo
            InstructorCheck.setSelected(false);
            InstructorCheck.setBackground(Color.WHITE);
            InstructorCheck.setForeground(Color.BLACK);
        } else {
            // Restaurar el color de fondo cuando no está seleccionado
            AprendizCheck.setBackground(Color.WHITE);
            AprendizCheck.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_AprendizCheckItemStateChanged

    
        private void initCardLayout() {
        cardLayout = new CardLayout();
        MainPanelModUser.setLayout(cardLayout);

        ModAprendizSubPanel apredizPanel = new ModAprendizSubPanel();
        ModInstructorSubPanel instructorPanel = new ModInstructorSubPanel();
        // Agrega los paneles al CardLayout
        MainPanelModUser.add(apredizPanel, "AprendizPanel");
        MainPanelModUser.add(instructorPanel, "InstructorPanel");

        // Muestra el panel del aprendiz por defecto (opcional)
        cardLayout.show(MainPanelModUser, "AprendizPanel");
    }

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AprendizCheck;
    private javax.swing.JToggleButton InstructorCheck;
    private javax.swing.JPanel MainPanelModUser;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
